'use strict';
let catalog, index=0, token=null, image=new Image();
const $=id=>document.getElementById(id);
async function api(path,body){const options=body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{};const response=await fetch(path,options);const value=await response.json();if(!response.ok)throw Error(value.error||'request failed');return value}
function reviewer(){return {id:$('reviewer').value.trim(),entered_by:'human',machine_assistance:true,previous_prediction_exposure:true,previous_annotation_exposure:$('prior').checked,exposure_notes:$('notes').value,confirmation:$('confirm').checked}}
function current(){return catalog.records[index]}
function draw(){const row=current(),canvas=$('canvas'),ctx=canvas.getContext('2d');canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;ctx.drawImage(image,0,0);const b=row.selected_box_xyxy;if(b){ctx.strokeStyle='#ffe13b';ctx.lineWidth=3;ctx.strokeRect(b[0],b[1],b[2]-b[0],b[3]-b[1])}}
function show(){if(!catalog.records.length){$('message').textContent='대응 검수가 필요한 선택 객체가 없습니다.';return}const row=current();$('progress').textContent=`${index+1}/${catalog.records.length} · 완료 ${catalog.counts.reviewed} · 대기 ${catalog.counts.pending}`;$('frame').textContent=`프레임 ${row.frame_id} · 대상 ID ${row.target_object_id} · 후보 ${row.candidate_count}`;image.onload=draw;image.src='/api/image?frame_id='+encodeURIComponent(row.frame_id);token=null;for(const el of document.querySelectorAll('input[name=decision]'))el.checked=false;$('reason').value='';$('edit').value=''}
async function start(){try{const r=await api('/api/start',{frame_id:current().frame_id,reviewer:reviewer()});token=r.token;if(r.record){document.querySelector(`input[name=decision][value=${r.record.decision}]`).checked=true;$('reason').value=r.record.decision_reason||''}$('message').textContent='검수 세션이 시작되었습니다.'}catch(e){$('message').textContent=e.message}}
async function save(){try{if(!token)throw Error('먼저 검수 시작/재개를 누르세요.');const choice=document.querySelector('input[name=decision]:checked');if(!choice)throw Error('same/different/undetermined 중 하나를 직접 선택하세요.');const r=await api('/api/save',{token,record:{frame_id:current().frame_id,decision:choice.value,decision_reason:$('reason').value,edit_reason:$('edit').value}});catalog.counts=r.counts;$('message').textContent='저장되었습니다.';show()}catch(e){$('message').textContent=e.message}}
$('start').onclick=start;$('save').onclick=save;$('prev').onclick=()=>{index=(index-1+catalog.records.length)%catalog.records.length;show()};$('next').onclick=()=>{index=(index+1)%catalog.records.length;show()};
api('/api/catalog').then(value=>{catalog=value;show()}).catch(e=>$('message').textContent=e.message);
