"""Refresh aggregate views without overwriting the approved publication policy."""
from . import common as C

def main():
    # Finalized author/release text is deliberately not regenerated by the
    # original pre-approval report template below.
    authorization=C.DOC/'PUBLICATION_AUTHORIZATION.json'
    if authorization.exists() and C.read(authorization)['status']=='USER_AUTHORIZED':
        results=C.read(C.DOC/'WOOD_RESULTS.json');audit=C.read(C.DOC/'MATERIAL_PAPER_AUDIT.json')
        public=C.read(C.DOC/'PUBLIC_RESULTS.json')
        assert public['groups']==results['groups']
        C.save(C.DOC/'PUBLIC_FINAL_AUDIT.json',dict(status=audit['status'],checks=audit['checks'],tests_passed=audit['tests_passed'],
            publication_scope='Authorized reproducibility metadata, figures and manuscript; original RGB, coordinate arrays, camera matrices and weights excluded',
            PDF_pages=13,PDF_visual_review_pages=[1,5,6],raw_RGB_or_coordinate_arrays_published=False))
        print('AUTHORIZED_PUBLIC_AGGREGATES_VERIFIED; finalized prose preserved',flush=True)
        return
    results=C.read(C.DOC/'WOOD_RESULTS.json');decision=C.read(C.DOC/'MATERIAL_FINAL_DECISION.json')
    audit=C.read(C.DOC/'MATERIAL_PAPER_AUDIT.json')
    # Do not serialize checkpoint paths, image catalogues, calibration, source
    # bindings, per-point arrays, environment listings or private-file hashes.
    C.save(C.DOC/'PUBLIC_RESULTS.json',dict(material_decision=decision['material_decision'],
        groups=results['groups'],severity_available=results['severity_available'],
        Q1_WOOD=results['Q1_WOOD'],frames=45,recordings=2,
        legacy_teacher_quality_not_verified=True,independent_confirmation=False,
        new_fits=2,updates_per_fit=320,train_unique=361,accepted_shared=676,candidates=1000))
    C.save(C.DOC/'PUBLIC_FINAL_AUDIT.json',dict(status=audit['status'],checks=audit['checks'],tests_passed=audit['tests_passed'],
        private_provenance_and_checkpoint_bindings='Retained locally; not included in this public release',
        PDF_pages=13,PDF_visual_review_pages=[1,5,6],raw_RGB_or_coordinate_arrays_published=False))
    C.save(C.DOC/'TRAINING_COMPLETION_KO.md','# Wood 짝지은 학습 완료\n\n신규 fit은 WOOD_RAW_LR5·WOOD_REF_LR5 두 개뿐이며 각5epoch/320update를 실제 optimizer hook으로 확인했다. 고정 Replay9장/38코너 교사와 동일 R0 초기값을 사용했다. 동일 후보1,000장→공통통과676장→고정표본고유361장/실사512슬롯, 기존합성512슬롯이다. RAW/REF 이미지순서·박스·support·source replay 일치, 유효좌표만 다름을 검증했다. 744개 protected state가 저장checkpoint에서도exact 유지됐다. RAW46.7초·REF46.4초, final last만 사용했다.\n\n기존Plastic에는 없던 공통감독최소6점 검사가 실행전에발견되어 제거했다. 기존Plastic도4/5점 이미지를사용한다는원자료로정정했으며 원판정은로컬에보존했다. 승인집합676장은전부유지했고 threshold·교사·학습량을바꾸지않았다. 성능결과를본후재시도한학습은0회다.\n\n실제 checkpoint/입력목록/출처해시는 로컬의 상세재현파일에보존했다. 원본RGB·원시좌표·카메라행렬·모델가중치는공개하지않는다.\n')
    C.save(C.DOC/'PUBLICATION_NOTICE_KO.md','# 이번 공개본의 범위\n\n공개 저장소의 상세 경로·해시 메타데이터 push가 안전검사에서 차단되었다. 사용자의 메타데이터 공개 허용 응답 전에는 해당 새파일을커밋하지않고 로컬에보존한다. 이번후속push에는 실측집계, 한국어표·허용된평가사례그림, 실험코드, 영문원고/PDF, 메타데이터없는검사결과만포함한다. 과거이미push된사전감사는삭제하지않는다.\n\n`PUBLIC_RESULTS.json`은전체그룹수치를, `PUBLIC_FINAL_AUDIT.json`은검사PASS를담는다. 상세 `WOOD_RESULTS.json`, `WOOD_TRAIN_PROTOCOL.json`, `FIT_*.json`, `MATERIAL_PAPER_AUDIT.json`, privatepool/calibration/environment목록등은로컬에있다. 공개축소본만으로원본데이터를복원할수없으며공개benchmark완전배포라고주장하지않는다.\n')
    C.save(C.DOC/'REPRODUCE_PUBLIC.md','# 공개본 재현 안내\n\n전체원자료·좌표·checkpoint를보유한로컬환경에서는다음순서로동일namespace의완료캐시와계약을검증한다. 기존완료fit은다시학습하지않는다. GitHub공개본은집계와코드이며private자료없는freshclone만으로학습재현되지는않는다.\n\n```bash\npython -m scripts.research.pallet_material_selftrain_closure_v1.lock_method\npython -m scripts.research.pallet_material_selftrain_closure_v1.wood_inventory_audit\npython -m scripts.research.pallet_material_selftrain_closure_v1.prepare_wood\npython -m scripts.research.pallet_material_selftrain_closure_v1.pseudo_pool\npython -m scripts.research.pallet_material_selftrain_closure_v1.train_pair prepare\npython -m scripts.research.pallet_material_selftrain_closure_v1.train_pair WOOD_RAW_LR5\npython -m scripts.research.pallet_material_selftrain_closure_v1.train_pair WOOD_REF_LR5\npython -m scripts.research.pallet_material_selftrain_closure_v1.infer_eval\npython -m scripts.research.pallet_material_selftrain_closure_v1.score_eval\npython -m scripts.research.pallet_material_selftrain_closure_v1.material_report\npython -m scripts.research.pallet_material_selftrain_closure_v1.figures\npython -m scripts.research.pallet_material_selftrain_closure_v1.final_audit build\npython -m scripts.research.pallet_material_selftrain_closure_v1.final_audit audit\n```\n\n사전감사와현재소스의정정흔적을보존했다. 세부raw/corrected타깃출처와privateSHA검증은로컬의REPRODUCE.md/JSON을참조한다. 두material주표는기존Plastic320과신규Wood320으로구성되며 Plastic640은보조결과다. teacher/threshold/GT/selector변경은없다.\n')
    print('PUBLIC_AGGREGATES_READY',flush=True)

if __name__=='__main__':main()
