"""Evaluate sealed head observations with the same frozen solver and local line ablation."""
from collections import Counter
import copy
import time
import numpy as np
import cv2
from . import common as C
from .inference import hidden_mask,finish
from .evaluate import score,packet
from .point_line import solve as solve_lines,tests as line_tests

def run():
    from .solver import HypothesisBank
    seal=C.read(C.DOC/'OBSERVATION_SEAL.json');assert seal['complete']
    path=C.DOC/'LEARNED_OBSERVATIONS.jsonl.gz'
    assert C.sha(path)==seal['records']['sha256']
    assert not (C.DOC/'LEARNED_PREDICTIONS.jsonl.gz').exists()
    checks=line_tests();C.write(C.DOC/'POINT_LINE_CHECKS.json',dict(passed=True,checks=checks,
        offset_convention='normal dot projected_point minus offset',same_observations_as_point_only=True))
    bounds={r['id']:r for r in C.read(C.DOC/'INPUTS.json')['frames']}
    initial={r['id']:r['initial_pose'] for r in C.iter_rows(C.DOC/'OBSERVATIONS.jsonl.gz') if r['method']=='BASE_NO_MASK_STANDARD'}
    deploy=[];start=time.monotonic();counts=Counter();cv2.setNumThreads(1)
    C.write(C.DOC/'LEARNED_GEOMETRY_CODE_LOCK.json',dict(files=[C.binding(__file__),C.binding(__import__('pathlib').Path(__file__).with_name('point_line.py'))],
        point_line='soft_l1 fscale8 max50, rank6, no residual prior, remove source edges used by points'))
    with C.no_truth_reads():
        for observation in C.iter_rows(path):
            fid=observation['id'];f=bounds[fid];arm=observation['method'];original=np.asarray(f['points']['BASE'],float)
            q=np.full((9,2),np.nan);q[8]=original[8]
            for c in observation['corners']:q[c['id']]=c['xy']
            init=initial[fid];H,hd=hidden_mask(init)
            bank=HypothesisBank(q,f['K'],f['xyz'],image_size=(f['raw_hw'][1],f['raw_hw'][0]))
            # All three model arms share mask generated by original fixed Base pose.
            main=finish(bank,original,init,excluded=H,hidden=H,robust=True)
            methods=[(arm,main)]
            if arm=='IMAGE_ROLE':
                methods.extend([('IMAGE_ROLE_NO_MASK_ROBUST',finish(bank,original,init,robust=True)),
                    ('IMAGE_ROLE_STANDARD',finish(bank,original,init,excluded=H,hidden=H,robust=False))])
                allowed=set(bank.eligible)-set(H)
                obs=dict(corners=[c for c in observation['corners'] if c['id'] in allowed],lines=observation['lines'])
                # Intersections are the output observations. Keep actual selected q for nonhidden output.
                answer=solve_lines(obs,np.asarray(f['K']),np.asarray(f['xyz']),init,main['solver'],H)
                counts['point_line_paths']+=1
                counts['point_line_optimizer_starts']+=len(answer.get('attempts',[]))
                counts['point_line_nfev']+=sum(a.get('nfev',0) for a in answer.get('attempts',[]))
                new=answer['available'];fallback=not new and init['available'];out=original.copy()
                if new:
                    for c in observation['corners']:
                        if c['id'] not in H:out[c['id']]=c['xy']
                if new and H:out[H]=np.asarray(answer['projected'])[H]
                pose=answer if new else init;after,_=hidden_mask(pose) if new else ([],{})
                solver=dict(answer,used=[c['id'] for c in obs['corners']],eligible=list(bank.eligible),
                    inliers=[],fit_input_ids=[c['id'] for c in obs['corners']] if new else [],
                    operation_counts={},hypothesis_bank_counts={})
                # No thresholded point-PnP consensus is claimed for this local robust nonlinear ablation.
                pl=dict(solver=solver,actual_pose=pose,native_points=out,pose_available=pose['available'],new_pose_estimated=new,
                    fallback_used=fallback,no_pose=not pose['available'],hidden_reprojected=new and bool(H),hidden_initial=H,
                    hidden_after=after,hidden_set_changed=new and set(after)!=set(H),excluded=H,
                    reprojected_ids=H if new else [],reprojections_reused_as_observations=False,
                    output_status='NEW_POSE' if new else 'BASELINE_FALLBACK' if fallback else 'POSE_FAILURE',
                    local_point_line_refinement=True,independent_four_point_PnP=False)
                methods.append(('IMAGE_ROLE_POINT_LINE',pl))
            for method,result in methods:
                # Unlike hidden coordinates, selected nonhidden corners represent actual changed observations.
                if result['new_pose_estimated']:
                    out=np.asarray(result['native_points']).copy()
                    for c in observation['corners']:
                        if c['id'] not in result['hidden_initial']:out[c['id']]=c['xy']
                    result['native_points']=out
                result.update(input_points=q,initial_pose=init,mask_diagnostic=hd,oracle=False,
                    observation_raw_logits_sha256=observation.get('raw_logits_sha256'),
                    selected_queries=observation.get('selected_queries',0),selected_corner_ids=[c['id'] for c in observation['corners']],
                    all_no_match=observation.get('all_no_match',True),source_lines=[l['edge'] for l in observation['lines']],
                    correspondence_absence_not_used_to_fill_pose=True)
                deploy.append(packet(f,method,result))
            counts.update(bank.ledger)
    C.save_rows(C.DOC/'LEARNED_GEOMETRY_SEALED.jsonl.gz',deploy)
    # Live truth access is only after the complete learned geometry output has been sealed.
    C.source_modules()
    from scripts.research.pallet_training_free_compare_20261007_v1.common import load_real
    E,frames,targets,_,_=load_real();frames={f['id']:f for f in frames}
    old={r['id']:r for r in C.iter_rows(C.DOC/'FIXED_CONTROLS.jsonl.gz') if r['method']=='BASE'}
    labels={(r['frame_id'],r['corner_id']):r['category'] for r in C.read(C.ROOT/'_docs/experiments/pallet_combined_closeout_20261003_v1/closeout_20261006_v1/visibility_square/STATIC_VISIBILITY_MERGE_AUDIT.json')['rows'] if r['population']=='DEV319'}
    rows=[]
    for r in deploy:
        fid=r['id'];row=score(E,frames[fid],targets[fid],r);prior=old[fid]
        perm=targets[fid]['permutations'][prior['corner'].get('branch',0)][:8]
        states=[labels.get((fid,k),'UNANNOTATED') for k in perm];H=set(row['hidden_initial']);known={k for k,s in enumerate(states) if s!='UNANNOTATED'}
        humanH={k for k,s in enumerate(states) if s=='SELF_OCCLUDED'}
        row['mask_audit']=dict(human_states_native=states,oracle_phase_only_for_audit=True,
            known_ids=sorted(known),false_excluded_visible=sorted(H&{k for k,s in enumerate(states) if s=='DIRECT_VISIBLE'}),
            false_retained_self=sorted((humanH-H)&set(row['solver']['eligible'])),
            mask_wrong_on_known=bool((H^humanH)&known),remaining_human_direct_visible=len(set(row['solver']['used'])&{k for k,s in enumerate(states) if s=='DIRECT_VISIBLE'}))
        row['baseline_pose']=prior['pose'];row['baseline_corner']=prior['corner'];rows.append(row)
    assert len(rows)==1914
    C.save_rows(C.DOC/'LEARNED_PREDICTIONS.jsonl.gz',rows)
    C.write(C.DOC/'LEARNED_POSE_EXECUTION.json',dict(complete=True,rows=len(rows),models=3,point_solver_paths=1595,
        point_line_paths=319,counts=dict(counts),seconds=time.monotonic()-start,
        initial_Base_pose_reused_from_same_fixed_numeric_inputs=True,GT_canary=True,
        raw_observations=C.binding(path),final_sealed=C.binding(C.DOC/'LEARNED_GEOMETRY_SEALED.jsonl.gz')))
    print('LEARNED_EVAL COMPLETE',len(rows),'seconds',time.monotonic()-start,flush=True)

if __name__=='__main__':run()
