'use strict';
const el = id => document.getElementById(id);
const copy = object => JSON.parse(JSON.stringify(object));
const axes = ['external_occlusion','self_occlusion','out_of_frame','definition_uncertain'];
const axisLabels = ['외부 물체에 가림','자기 가림','화면 밖','정의 미확인 / 직접 클릭 불가'];
let catalog, frame, session, record, selectedId = 0, undoStack = [], localDirty = false;
let image = new Image(), imageReady = false, loadingGeneration = 0;
let view = {scale:1,tx:0,ty:0,viewportWidth:1,viewportHeight:1}, drag = null;
const canvas = el('rawCanvas'), context = canvas.getContext('2d');

function message(text,error=false){el('message').textContent=text;el('message').classList.toggle('error',error);el('message').style.display='block';clearTimeout(message.timer);message.timer=setTimeout(()=>el('message').style.display='none',6500);}
async function api(path,data){const response=await fetch(path,data ? {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)} : {});const result=await response.json();if(!response.ok)throw Error(result.error||'요청 실패');return result;}
function attempt(fn){return async()=>{try{await fn();}catch(error){message(error.message,true);}};}
function reviewer(){const answers=['machine','predExposure','annExposure'].map(id=>el(id).value);if(!el('reviewerId').value.trim()||answers.some(x=>!x)||!el('provenance').checked)throw Error('검수자 ID와 세 가지 노출 이력·직접 확인을 입력하세요.');return {id:el('reviewerId').value.trim(),entered_by:'human',machine_assistance:answers[0]==='yes',previous_prediction_exposure:answers[1]==='yes',previous_annotation_exposure:answers[2]==='yes',exposure_notes:el('exposureNotes').value,confirmation:true};}
function blankRecord(){return {frame_id:frame.frame_id,review_pass:el('pass').value,status:'draft',reviewer:reviewer(),object:{presence:null,target_object_id:null,target_identity_confirmed:false,notes:''},corners:catalog.contract.corners.map(c=>({id:c.id,visibility:null,external_occlusion:false,self_occlusion:false,out_of_frame:false,definition_uncertain:false,definition_confirmed:false,x:null,y:null,reason:''})),skip_reason:'',edit_reason:'',interaction_log:[]};}
function currentCorner(){return record.corners.find(c=>c.id===selectedId);}
function requireSession(){if(!session)throw Error('선택 프레임 검수 시작 / 재개를 먼저 누르세요.');if(JSON.stringify(reviewer())!==JSON.stringify(record.reviewer))throw Error('검수자 이력이 바뀌었습니다. 다시 검수를 시작하세요.');}
function snapshot(kind){undoStack.push(copy(record));if(undoStack.length>100)undoStack.shift();record.interaction_log=record.interaction_log||[];record.interaction_log.push({action:kind,performed_at:new Date().toISOString()});localDirty=true;}
function draw(){const dpr=window.devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;if(!w||!h)return;if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);}view.viewportWidth=w;view.viewportHeight=h;context.setTransform(dpr,0,0,dpr,0,0);context.fillStyle='#030609';context.fillRect(0,0,w,h);if(!imageReady)return;context.save();context.translate(view.tx,view.ty);context.scale(view.scale,view.scale);context.drawImage(image,0,0);context.restore();if(record&&session){record.corners.forEach(c=>{if(c.visibility==='direct_visible'&&Number.isFinite(c.x)&&Number.isFinite(c.y)){const x=c.x*view.scale+view.tx,y=c.y*view.scale+view.ty;context.beginPath();context.arc(x,y,c.id===selectedId?6:4,0,Math.PI*2);context.strokeStyle='#79dbff';context.lineWidth=2;context.stroke();context.font='bold 14px system-ui';context.fillStyle='#79dbff';context.fillText(String(c.id),x+8,y-6);}});}}
function fit(){if(!imageReady)return;view.scale=Math.min(canvas.clientWidth/image.naturalWidth,canvas.clientHeight/image.naturalHeight)*0.96;view.tx=(canvas.clientWidth-image.naturalWidth*view.scale)/2;view.ty=(canvas.clientHeight-image.naturalHeight*view.scale)/2;draw();}
function zoom(factor,point){const rect=canvas.getBoundingClientRect();view=ReviewCoords.zoomAt(point||{x:rect.left+rect.width/2,y:rect.top+rect.height/2},rect,view,factor);draw();}
function counts(){const c=catalog.counts;el('counts').textContent=`주 검수 ${c.primary_reviewed}/${c.total_primary} · 재검수 ${c.repeat_reviewed}/${c.total_repeat} · 미완료 ${c.incomplete_primary+c.incomplete_repeat} · 진행 중 ${c.drafts} · 건너뜀 ${c.skipped} · 직접 가시 클릭 ${c.visible_corners} · WAITING_HUMAN`;}
function frameList(){return catalog.frames.filter(f=>el('pass').value==='primary'||f.repeat_review);}
function populateFrames(preserve){const select=el('frameSelect');select.replaceChildren();frameList().forEach(f=>{const option=document.createElement('option');option.value=f.frame_id;const status=catalog.statuses[f.frame_id+'|'+el('pass').value]||'미검수';option.textContent=`${f.frame_id} · ${status}`;select.append(option);});if(preserve)select.value=preserve;}
async function loadFrame(){if(localDirty&&!window.confirm('저장하지 않은 변경이 있습니다. 다른 프레임으로 이동할까요?')){el('frameSelect').value=frame.frame_id;return;}session=null;record=null;undoStack=[];localDirty=false;frame=catalog.frames.find(f=>f.frame_id===el('frameSelect').value);const generation=++loadingGeneration;imageReady=false;draw();el('frameMeta').textContent=`프레임 ${frame.frame_id} | 세션 ${frame.session_id} | 저장 index ${frame.saved_frame_index}\n센서 ${frame.camera_sensor_timestamp_ms} ms | ${frame.camera_timestamp_domain||'도메인 미기록'} | 원본 ${frame.width} × ${frame.height}`;el('frameMeta').style.whiteSpace='pre-wrap';el('sessionInfo').textContent=el('pass').value==='repeat'?'재검수: 첫 검수 좌표 없이 시작합니다. 같은 사람 반복인지 실제 ID로 기록합니다.':'검수자 이력을 입력한 뒤 검수 시작 / 재개를 누르세요.';el('corners').replaceChildren();el('presence').value='';el('objectId').value='';el('objectConfirmed').checked=false;el('objectNotes').value='';el('reason').value='';const nextImage=new Image();nextImage.onload=()=>{if(generation!==loadingGeneration)return;if(nextImage.naturalWidth!==frame.width||nextImage.naturalHeight!==frame.height){message('원본 이미지 치수가 manifest와 다릅니다.',true);return;}image=nextImage;imageReady=true;fit();};nextImage.onerror=()=>message('원본 이미지를 읽지 못했습니다.',true);nextImage.src='/api/image?frame_id='+encodeURIComponent(frame.frame_id);}
function reflectObject(){el('presence').value=record.object.presence||'';el('objectId').value=record.object.target_object_id||'';el('objectConfirmed').checked=record.object.target_identity_confirmed;el('objectNotes').value=record.object.notes||'';}
function renderCorners(){el('corners').replaceChildren();record.corners.slice().sort((a,b)=>a.id-b.id).forEach(c=>{const row=document.createElement('div');row.className='corner'+(c.id===selectedId?' selected':'');const head=document.createElement('div');head.className='corner-head';const pick=document.createElement('button');pick.textContent='ID '+c.id;pick.onclick=()=>{selectedId=c.id;renderCorners();draw();};head.append(pick);const select=document.createElement('select');[['','미검수'],['direct_visible','직접 가시'],['not_direct_visible','직접 가시 아님'],['uncertain','판단 불가 / 직접 클릭 불가']].forEach(([value,label])=>{const option=document.createElement('option');option.value=value;option.textContent=label;select.append(option);});select.value=c.visibility||'';select.onchange=attempt(()=>{requireSession();snapshot('corner_state');c.visibility=select.value||null;if(c.visibility!=='direct_visible'){c.x=null;c.y=null;}if(c.visibility==='uncertain')c.definition_uncertain=true;selectedId=c.id;renderCorners();draw();});head.append(select);const xy=document.createElement('span');xy.className='coordinate';xy.textContent=c.x===null?'좌표 없음':`${c.x.toFixed(3)}, ${c.y.toFixed(3)}`;head.append(xy);row.append(head);const axisRow=document.createElement('div');axisRow.className='axes';axes.forEach((key,i)=>{const label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.checked=c[key];check.onchange=attempt(()=>{requireSession();snapshot('occlusion_axis');c[key]=check.checked;if(check.checked&&c.visibility==='direct_visible'){c.visibility='not_direct_visible';c.x=null;c.y=null;}renderCorners();draw();});label.append(check,document.createTextNode(axisLabels[i]));axisRow.append(label);});row.append(axisRow);const physical=document.createElement('label');physical.className='physical';const confirm=document.createElement('input');confirm.type='checkbox';confirm.checked=c.definition_confirmed;confirm.onchange=attempt(()=>{requireSession();snapshot('physical_corner_confirmation');c.definition_confirmed=confirm.checked;if(confirm.checked)c.definition_uncertain=false;else if(c.visibility==='direct_visible'){c.visibility='uncertain';c.definition_uncertain=true;c.x=null;c.y=null;}renderCorners();draw();});physical.append(confirm,document.createTextNode('이 canonical ID가 실제 보이는 재료 꼭짓점에 대응함을 확인'));row.append(physical);const reason=document.createElement('input');reason.className='corner-reason';reason.placeholder='판단 근거 / 직접 클릭 불가 사유';reason.value=c.reason;reason.onchange=attempt(()=>{requireSession();snapshot('corner_reason');c.reason=reason.value;});row.append(reason);el('corners').append(row);});}
async function begin(){if(!imageReady)throw Error('검증된 원본 이미지가 필요합니다.');const result=await api('/api/start',{frame_id:frame.frame_id,review_pass:el('pass').value,reviewer:reviewer()});session=result.token;record=result.record||blankRecord();record.reviewer=reviewer();if(record.status==='skipped'&&record.corners.length===0){record=blankRecord();record.edit_reason='';}undoStack=[];localDirty=false;reflectObject();renderCorners();draw();el('sessionInfo').textContent=`검수 시작 ${result.started_at} · ${record.review_pass==='repeat'?'첫 검수 좌표 미사용':'원본 좌표로 기록'} · 저장 전 사람 판단 확인 필요`;message(result.record?'같은 차수의 저장 기록을 불러왔습니다. 제출 기록을 수정하면 사유가 필요합니다.':'빈 주석으로 시작했습니다.');}
function changeObject(){requireSession();snapshot('object_review');record.object={presence:el('presence').value||null,target_object_id:el('objectId').value.trim()||null,target_identity_confirmed:el('objectConfirmed').checked,notes:el('objectNotes').value};if(record.object.presence!=='present'||!record.object.target_identity_confirmed){record.corners.forEach(c=>{if(c.visibility==='direct_visible'){c.visibility='uncertain';c.definition_uncertain=true;c.x=null;c.y=null;}});renderCorners();draw();}}
async function save(status){requireSession();record.status=status;record.edit_reason=el('reason').value;record.skip_reason=status==='skipped'?el('reason').value:'';const outgoing=copy(record);if(status==='skipped')outgoing.corners=[];const result=await api('/api/save',{token:session,record:outgoing});record=result.record;localDirty=false;catalog=await api('/api/catalog');counts();populateFrames(frame.frame_id);if(status==='skipped'){session=null;el('corners').replaceChildren();draw();}else renderCorners();message(status==='draft'?'진행 중 기록 저장: 정확도 참조에 포함되지 않습니다.':`사람 검수 ${status==='skipped'?'건너뜀':'완료'} 저장. JSON 내보내기에서 제출된 범위만 받습니다.`);}
canvas.addEventListener('contextmenu',event=>event.preventDefault());
canvas.addEventListener('pointerdown',event=>{if(el('panMode').checked||event.button===2||event.shiftKey){drag={x:event.clientX,y:event.clientY,tx:view.tx,ty:view.ty};canvas.setPointerCapture(event.pointerId);return;}try{requireSession();const c=currentCorner();if(!c||c.visibility!=='direct_visible'||!c.definition_confirmed||axes.some(key=>c[key]))throw Error('선택 ID를 직접 가시로 표시하고 물리 꼭짓점 대응을 확인하세요.');if(record.object.presence!=='present'||!record.object.target_identity_confirmed||!record.object.target_object_id)throw Error('대상 객체 존재·ID·대응 확인이 필요합니다.');const p=ReviewCoords.screenToOriginal({x:event.clientX,y:event.clientY},canvas.getBoundingClientRect(),view);if(p.x<0||p.y<0||p.x>=frame.width||p.y>=frame.height)throw Error('원본 이미지 내부만 클릭하세요.');snapshot('manual_raw_click');c.x=p.x;c.y=p.y;renderCorners();draw();}catch(error){message(error.message,true);}});
canvas.addEventListener('pointermove',event=>{const rect=canvas.getBoundingClientRect();if(drag){view.tx=drag.tx+(event.clientX-drag.x)*view.viewportWidth/rect.width;view.ty=drag.ty+(event.clientY-drag.y)*view.viewportHeight/rect.height;draw();}if(imageReady){const p=ReviewCoords.screenToOriginal({x:event.clientX,y:event.clientY},rect,view);el('coordReadout').textContent=`원본 좌표 ${p.x.toFixed(3)}, ${p.y.toFixed(3)} · 배율 ${view.scale.toFixed(3)}`;}});
canvas.addEventListener('pointerup',()=>drag=null);canvas.addEventListener('pointercancel',()=>drag=null);canvas.addEventListener('wheel',event=>{event.preventDefault();zoom(event.deltaY<0?1.2:1/1.2,{x:event.clientX,y:event.clientY});},{passive:false});
el('fit').onclick=fit;el('zoomIn').onclick=()=>zoom(1.25);el('zoomOut').onclick=()=>zoom(0.8);el('begin').onclick=attempt(begin);el('draft').onclick=attempt(()=>save('draft'));el('submit').onclick=attempt(()=>save('reviewed'));el('skip').onclick=attempt(()=>save('skipped'));
el('undo').onclick=attempt(()=>{requireSession();if(!undoStack.length)throw Error('취소할 변경이 없습니다.');record=undoStack.pop();record.interaction_log.push({action:'undo',performed_at:new Date().toISOString()});localDirty=true;reflectObject();renderCorners();draw();});
el('markUncertain').onclick=attempt(()=>{requireSession();snapshot('mark_unreviewed_uncertain');record.corners.forEach(c=>{if(c.visibility===null){c.visibility='uncertain';c.definition_uncertain=true;c.reason=record.object.presence==='absent'?'대상 객체 부재':'사람 판단: 정의 대응 또는 직접 가시 확인 불가';}});renderCorners();draw();});
['presence','objectId','objectConfirmed','objectNotes'].forEach(id=>el(id).onchange=attempt(changeObject));el('frameSelect').onchange=attempt(loadFrame);el('pass').onchange=attempt(async()=>{if(localDirty&&!window.confirm('저장하지 않은 변경이 있습니다. 차수를 바꿀까요?')){el('pass').value=record.review_pass;return;}localDirty=false;populateFrames();await loadFrame();});
function navigate(delta){const list=frameList(),index=list.findIndex(f=>f.frame_id===frame.frame_id);if(index+delta>=0&&index+delta<list.length){el('frameSelect').value=list[index+delta].frame_id;return loadFrame();}}
el('previous').onclick=attempt(()=>navigate(-1));el('next').onclick=attempt(()=>navigate(1));new ResizeObserver(draw).observe(canvas);window.addEventListener('beforeunload',event=>{if(localDirty){event.preventDefault();event.returnValue='';}});
async function initialize(){catalog=await api('/api/catalog');counts();el('objectDefinition').textContent=catalog.contract.object_definition;el('contractWarning').textContent=catalog.contract.warning||'';catalog.contract.corners.forEach(c=>{const line=document.createElement('p');line.textContent=`${c.name}: ${c.definition}`;el('cornerDefinitions').append(line);});populateFrames();await loadFrame();}
function conceptualDiagram(){
  const corners=catalog.contract.corners;
  if(!corners.every(c=>Array.isArray(c.xyz_m)&&c.xyz_m.length===3&&c.xyz_m.every(Number.isFinite)))return;
  const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');
  svg.setAttribute('viewBox','0 0 320 245');svg.setAttribute('role','img');svg.setAttribute('aria-label','외부 계약에서 읽은 canonical ID와 물체 X Y Z 축의 개념 도식');svg.style.width='100%';svg.style.maxHeight='240px';
  const extents=[0,1,2].map(axis=>Math.max(...corners.map(c=>Math.abs(c.xyz_m[axis]))));
  if(extents.some(x=>x===0))return;
  const project=xyz=>({x:155+xyz[0]/extents[0]*64-xyz[2]/extents[2]*44,y:102+xyz[0]/extents[0]*25+xyz[2]/extents[2]*25+xyz[1]/extents[1]*28});
  function line(a,b,color,width=1.3){const item=document.createElementNS(ns,'line');[['x1',a.x],['y1',a.y],['x2',b.x],['y2',b.y],['stroke',color],['stroke-width',width]].forEach(([k,v])=>item.setAttribute(k,v));svg.append(item);}
  function label(point,text,color){const item=document.createElementNS(ns,'text');item.setAttribute('x',point.x);item.setAttribute('y',point.y);item.setAttribute('fill',color);item.setAttribute('font-size','14');item.setAttribute('font-weight','600');item.textContent=text;svg.append(item);}
  corners.forEach((c,i)=>corners.slice(i+1).forEach(other=>{if(c.xyz_m.filter((value,k)=>value!==other.xyz_m[k]).length===1)line(project(c.xyz_m),project(other.xyz_m),'#829bb6');}));
  const origin=project([0,0,0]);
  [[0,'+X','#ff9f9f'],[1,'+Y (아래)','#9ee0b3'],[2,'+Z','#aabaff']].forEach(([axis,text,color])=>{const xyz=[0,0,0];xyz[axis]=extents[axis]*1.6;const endpoint=project(xyz);line(origin,endpoint,color,2.5);label({x:endpoint.x-8,y:endpoint.y+17},text,color);});
  corners.forEach(c=>{const p=project(c.xyz_m),circle=document.createElementNS(ns,'circle');circle.setAttribute('cx',p.x);circle.setAttribute('cy',p.y);circle.setAttribute('r','10');circle.setAttribute('fill','#1b3851');svg.append(circle);label({x:p.x-4,y:p.y+5},String(c.id),'#b9eeff');});
  el('cornerDiagram').append(svg);
}
initialize().then(conceptualDiagram).catch(error=>message(error.message,true));
