"""Standalone scalar audit of the fixed sparse LOCAL point/line C2 path.

Freeze completed GT-free geometry and this source before the audit's arithmetic.
Only stdlib is imported. No production solver, model, image, GT, optimizer,
OpenCV, NumPy, SVD or production Jacobian is invoked. Forward rotation,
projection and point/line Jacobian rows are reconstructed with scalar algebra.
Stored singular values are recounted, not independently regenerated by SVD.
"""
from __future__ import annotations

import argparse
from collections import Counter
import gzip
import hashlib
import json
import math
import os
from pathlib import Path
import struct
import time

REPO = Path(__file__).resolve().parents[3]
CODE = Path(__file__).resolve().parent
DOC = REPO / '_docs/experiments/pallet_sparse_local_line_20261010_v9'
PRIVATE = Path('/tmp/pallet-sparse-local-line-private-20261010-v9')
PARENT = REPO / '_docs/experiments/pallet_three_head_observation_20261010_v7'
POINT = REPO / '_docs/experiments/pallet_same_observation_controls_20261010_v8'
COHORT = REPO / '_docs/experiments/pallet_kp_corrected_supervision_20261010_v1/COHORT.json'
METHOD = 'ROLE_BOUNDARY_LOCAL_POINT_LINE'
POINT_METHODS = ('ROLE_BOUNDARY_H_ROBUST', 'ROLE_BOUNDARY_H_STANDARD', 'ROLE_BOUNDARY_NO_MASK_ROBUST')
PARENT_METHODS = ('IMAGE_ROLE_BOUNDARY_ONLY', 'GEOMETRY_ONLY_BOUNDARY_ONLY',
    'IMAGE_NO_ROLE_BOUNDARY_ONLY', 'GEOMETRY_ONLY_CORNERWISE_HYBRID',
    'IMAGE_NO_ROLE_CORNERWISE_HYBRID', 'IMAGE_ROLE_CORNERWISE_HYBRID',
    'N3_INDEPENDENT_ROBUST_H', 'N3_INDEPENDENT_ROBUST_NO_MASK')
HEADS = ('GEOMETRY_ONLY', 'IMAGE_NO_ROLE', 'IMAGE_ROLE')
EDGES = ((0, 1), (1, 2), (2, 3), (3, 0), (4, 5), (5, 6), (6, 7), (7, 4), (0, 4), (1, 5), (2, 6), (3, 7))
PHYSICAL = {0, 2, 4, 6, 8, 9, 10, 11}
CAL = {0, 2, 4, 8, 9, 10, 11}
CHECKPOINT = '882a6eddc964258abfbc1ad3baeee380ab9fac42b3b90c7f64166bd98d777d5d'
ATOL, RTOL, RANK, TIE = 1e-7, 1e-12, 1e-10, 1e-8
OUTPUTS = ('VALIDATION_PROTOCOL.json', 'VALIDATION_STARTED.json', 'VALIDATION_CHECKS.json')
LOCAL_KEYS = ('local_solve_calls', 'start_sources_examined', 'local_start_entries', 'local_optimizer_calls',
    'local_optimizer_completions', 'local_start_cache_hits', 'optimizer_residual_calls',
    'optimizer_jacobian_calls', 'optimizer_projectPoints_calls', 'geometry_diagnostic_calls',
    'diagnostic_projectPoints_calls', 'candidate_Rodrigues_calls', 'seed_Rodrigues_calls',
    'candidate_validation_calls', 'hidden_reprojection_assignments')
PRIMITIVES = ('solvePnP', 'solvePnPGeneric', 'solvePnPRefineLM', 'projectPoints', 'Rodrigues', 'cornerSubPix')
TRUTH = {'corner', 'pose', 'GT', 'ground_truth', 'reference_pose', 'human_states_native',
    'mask_audit', 'baseline_corner', 'baseline_pose'}
LIMITS = dict(new_model_GT_image_optimizer_OpenCV_PnP_ray_training_production_Jacobian_SVD_calls=0,
    scalar_forward_rotation_projection_and_J_rows_independent=True,
    stored_SVD_singular_values_recount_only=True, local_rank6_is_not_global_uniqueness=True,
    initial_pose_is_LOCAL_start_not_residual_prior=True,
    inlier8px_subset_rank_is_diagnostic_not_acceptance_gate=True,
    NEW_is_numerical_LOCAL_output_not_accuracy_success=True,
    initial_rank_or_modeled_edge_collapse_does_not_veto_start=True,
    no_unused_lines_three_points_is_point_LOCAL_not_independent_P3P=True,
    no_new_unseen_policy=True, same_existing_ROLE_observations=True,
    source_line_CAL_support_does_not_certify_real_physical_ownership=True,
    own_freeze_after_complete_GT_free_geometry_before_own_arithmetic=True,
    float_hash='Null cannot identify original NaN payload. Normalized line factor SHA joins stored witnesses; scalar normalization is checked numerically, not claimed byte-identical.',
    candidate_count='Stored valid returned numeric branches, including rank-rejected branches. Chosen rechecks counted separately.',
    actual_optimizer_counts='Recorded live entries and callback counters joined to all preserved attempts; no new optimizer execution.',
    hardware='Recorded resource/protection snapshots only; historical hardware authenticity and transient interference are not independently proven.',
    no_performance_based_changes=True, no_automatic_retry=True)


def require(value, reason):
    if not value:
        raise ValueError(reason)


def read(path):
    with Path(path).open(encoding='utf-8') as stream:
        return json.load(stream)


def rows(path):
    with gzip.open(path, 'rt', encoding='utf-8') as stream:
        for line in stream:
            require(bool(line.strip()), 'empty stored JSONL row')
            yield json.loads(line)


def binding(path):
    path = Path(path).absolute()
    require(path.is_file() and not any(p.is_symlink() for p in (path, *path.parents)), 'missing/symlink input ' + str(path))
    digest = hashlib.sha256()
    with path.open('rb') as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b''):
            digest.update(block)
    path = path.resolve()
    return dict(path=str(path.relative_to(REPO)) if path.is_relative_to(REPO) else path.name,
                bytes=path.stat().st_size, sha256=digest.hexdigest())


def same_binding(a, b):
    return isinstance(a, dict) and isinstance(b, dict) and all(a.get(k) == b.get(k) for k in ('bytes', 'sha256'))


def semantic(value):
    return hashlib.sha256(json.dumps(value, sort_keys=True, separators=(',', ':'), allow_nan=False).encode()).hexdigest()


def safe(value):
    if isinstance(value, dict):
        return {str(k): safe(v) for k, v in value.items()}
    if isinstance(value, (set, frozenset)):
        return sorted([safe(v) for v in value], key=lambda v: json.dumps(v, sort_keys=True))
    if isinstance(value, (list, tuple)):
        return [safe(v) for v in value]
    return repr(value) if isinstance(value, float) and not math.isfinite(value) else value


def write_new(path, value):
    with Path(path).open('x', encoding='utf-8') as stream:
        json.dump(safe(value), stream, ensure_ascii=False, indent=2, allow_nan=False)
        stream.write('\n'); stream.flush(); os.fsync(stream.fileno())


class Audit:
    def __init__(self):
        self.checks, self.failure_count, self.max_difference = 0, 0, 0.
        self.failures = []

    def ok(self, value, label, actual=None, expected=None):
        self.checks += 1
        if not value:
            self.failure_count += 1
            if len(self.failures) < 100:
                self.failures.append(dict(check=label, actual=safe(actual), expected=safe(expected)))

    def eq(self, actual, expected, label):
        self.ok(actual == expected, label, actual, expected)

    def near(self, actual, expected, label):
        if isinstance(expected, dict):
            valid = isinstance(actual, dict) and set(actual) == set(expected)
            self.ok(valid, label + '.fields', actual, expected)
            if valid:
                for k in expected:
                    self.near(actual[k], expected[k], label + '.' + k)
        elif isinstance(expected, (list, tuple)):
            valid = isinstance(actual, (list, tuple)) and len(actual) == len(expected)
            self.ok(valid, label + '.shape', actual, expected)
            if valid:
                for i, (a, e) in enumerate(zip(actual, expected)):
                    self.near(a, e, label + '.' + str(i))
        elif type(expected) in (int, float):
            valid = type(actual) in (int, float) and math.isfinite(actual) and math.isfinite(expected)
            d = abs(actual-expected) if valid else None
            if d is not None:
                self.max_difference = max(self.max_difference, d)
            self.ok(valid and d <= ATOL+RTOL*abs(expected), label, actual, expected)
        else:
            self.eq(actual, expected, label)


def finite(value, shape=()):
    if not shape:
        return type(value) in (int, float) and math.isfinite(value)
    return isinstance(value, (list, tuple)) and len(value) == shape[0] and all(finite(v, shape[1:]) for v in value)


def dot(a, b):
    return math.fsum(x*y for x, y in zip(a, b))


def mm(a, b):
    return [[dot(row, column) for column in zip(*b)] for row in a]


def eye():
    return [[float(i == j) for j in range(3)] for i in range(3)]


def skew(v):
    x, y, z = v
    return [[0., -z, y], [z, 0., -x], [-y, x, 0.]]


def rotation_and_right_J(r):
    require(finite(r, (3,)), 'nonfinite rotation vector')
    theta2 = dot(r, r)
    theta = math.sqrt(theta2)
    if theta < 1e-5:
        A = 1-theta2/6+theta2*theta2/120
        B = .5-theta2/24+theta2*theta2/720
        C = 1/6-theta2/120+theta2*theta2/5040
    else:
        A, B, C = math.sin(theta)/theta, (1-math.cos(theta))/theta2, (theta-math.sin(theta))/(theta2*theta)
    W, I = skew(r), eye()
    W2 = mm(W, W)
    R = [[I[i][j]+A*W[i][j]+B*W2[i][j] for j in range(3)] for i in range(3)]
    right = [[I[i][j]-B*W[i][j]+C*W2[i][j] for j in range(3)] for i in range(3)]
    return R, right


def dimensions(xyz):
    return [xyz] if abs(xyz[0]-xyz[2]) < 1e-9 else [xyz, [xyz[2], xyz[1], xyz[0]]]


def model(extents):
    a, b, c = [v/2 for v in extents]
    return [(-a, -b, -c), (a, -b, -c), (a, b, -c), (-a, b, -c),
            (-a, -b, c), (a, -b, c), (a, b, c), (-a, b, c)]


def forward(extents, z, K):
    require(finite(z, (6,)) and finite(extents, (3,)) and finite(K, (3, 3)), 'invalid scalar forward input')
    R, right = rotation_and_right_J(z[:3])
    uv, jac, depths = [], [], []
    for p in model(extents):
        camera = [dot(row, p)+t for row, t in zip(R, z[3:])]
        denominator = dot(K[2], camera)
        require(camera[2] > 1e-9 and denominator > 0, 'nonpositive candidate depth')
        numerator = [dot(row, camera) for row in K[:2]]
        uv.append([v/denominator for v in numerator]); depths.append(camera[2])
        dr = [[-v for v in row] for row in mm(mm(R, skew(p)), right)]
        dc = [row+identity for row, identity in zip(dr, eye())]
        perspective = [[(K[axis][j]*denominator-numerator[axis]*K[2][j])/(denominator*denominator)
                        for j in range(3)] for axis in range(2)]
        jac.append(mm(perspective, dc))
    return R, uv, jac, depths


def physical_rotation(R, dim):
    return R if dim == 0 else [[-row[2], row[1], row[0]] for row in R]


def equivalent(a, b, xyz):
    return (max(abs(x-y) for row, other in zip(a['projected'], b['projected']) for x, y in zip(row, other)) < 1e-5 and
        max(abs(x-y) for row, other in zip(a['R_physical'], b['R_physical']) for x, y in zip(row, other)) < 1e-5 and
        math.dist(a['centroid'], b['centroid'])/math.sqrt(dot(xyz, xyz)) < 1e-5)


def eligible(q, hw):
    h, w = hw
    return [k for k, xy in enumerate(q[:8]) if finite(xy, (2,)) and xy != [-1, -1] and 0 <= xy[0] < w and 0 <= xy[1] < h]


def factor_rows(uv, J, q, U, lines, modeled=False):
    residual, matrix = [], []
    for k in U:
        residual.extend([uv[k][i]-q[k][i] for i in range(2)])
        matrix.extend(J[k])
    for line in lines:
        a, b = EDGES[line['edge']]
        n = line['normal']
        if modeled:
            direction = [uv[b][i]-uv[a][i] for i in range(2)]
            length = math.hypot(*direction)
            require(length > 1e-12 and math.isfinite(length), 'projected_model_edge_degenerate')
            n = [-direction[1]/length, direction[0]/length]
        for k in (a, b):
            residual.append((dot(n, uv[k])-line['offset'])/math.sqrt(2))
            matrix.append([math.fsum(n[i]*J[k][i][j] for i in range(2))/math.sqrt(2) for j in range(6)])
    return residual, matrix


def rank_witness(w, matrix, audit, label):
    n = len(matrix)
    audit.eq(w['scalar_rows'], n, label + '.scalar_rows')
    audit.eq(w['local_only'], True, label + '.local_only')
    if not n:
        audit.eq(w['singular_values'], [], label + '.empty_singular')
        audit.eq(w['normalized_column_scale'], [], label + '.empty_scale')
        audit.eq(w['numerical_rank'], 0, label + '.empty_rank')
        audit.eq(w['condition_number'], None, label + '.empty_condition')
        return 0
    singular = w['singular_values']
    require(finite(singular, (min(n, 6),)) and all(v >= 0 for v in singular), 'invalid singular witness')
    audit.ok(all(a >= b for a, b in zip(singular, singular[1:])), label + '.descending')
    scales = [max(math.sqrt(math.fsum(row[j]**2 for row in matrix)), 1e-300) for j in range(6)]
    audit.near(w['normalized_column_scale'], scales, label + '.independent_column_norms')
    audit.eq(w['normalization'], 'unit L2 Jacobian columns', label + '.normalization')
    rank = sum(s > singular[0]*RANK for s in singular)
    audit.eq(w['numerical_rank'], rank, label + '.stored_singular_rank_recount')
    audit.near(w['condition_number'], singular[0]/singular[-1] if singular[-1] > 0 else None, label + '.condition')
    # Frobenius energy is independent of the stored singular spectrum.
    normalized_energy = math.fsum((row[j]/scales[j])**2 for row in matrix for j in range(6))
    audit.near(math.fsum(s*s for s in singular), normalized_energy, label + '.singular_frobenius_energy')
    return rank


def geometry_witness(g, uv, J, q, U, lines, audit, label):
    rr, observed = factor_rows(uv, J, q, U, lines)
    _, modeled = factor_rows(uv, J, q, U, lines, modeled=True)
    audit.eq(g['point_ids'], list(U), label + '.whole_U')
    audit.eq(g['line_edges'], [l['edge'] for l in lines], label + '.same_lines')
    audit.eq(g['modeled_normals_held_fixed_for_derivative'], True, label + '.modeled_normals_held_fixed')
    audit.eq(g['global_unique_pose_proven'], False, label + '.not_global_unique')
    audit.near(g['observed_normal_J'], observed, label + '.independent_observed_J')
    audit.near(g['modeled_normal_J'], modeled, label + '.independent_modeled_J')
    audit.near(g['actual_scalar_residuals_px'], rr, label + '.independent_scalar_residuals')
    split = 2*len(U)
    ranks = {}
    for name, matrix in (('observed_normal_joint', observed), ('modeled_normal_joint', modeled),
                        ('point_only', modeled[:split]), ('observed_normal_lines_only', observed[split:]),
                        ('modeled_normal_lines_only', modeled[split:])):
        ranks[name] = rank_witness(g[name], matrix, audit, label + '.' + name)
    return ranks, rr


def original_lines(obs, q, U, adopted, audit, label):
    corners = {int(c['id']): c for c in obs['corners']}
    require(len(corners) == len(obs['corners']), 'duplicate original corner')
    consumed = set()
    for k in adopted:
        if k not in U:
            continue
        c = corners[k]
        audit.eq(c['xy'], q[k], label + '.adopted_actual_corner.' + str(k))
        edges = c['edges']
        require(len(edges) == len(set(edges)) == 2 and all(type(e) is int and e in PHYSICAL and k in EDGES[e] for e in edges),
                'invalid physically supported adopted incident edges')
        consumed.update(edges)
    seen, accepted = {}, []
    for raw in obs['lines']:
        edge = raw['edge']
        require(type(edge) is int and 0 <= edge < 12, 'invalid original edge')
        identity = json.dumps(raw, sort_keys=True, separators=(',', ':'), allow_nan=False)
        if edge in seen:
            require(seen[edge] == identity, 'inconsistent original duplicate edge')
            continue
        seen[edge] = identity
        audit.eq(raw['endpoints'], list(EDGES[edge]), label + '.endpoint_identity.' + str(edge))
        if edge not in PHYSICAL:
            require(edge not in consumed, 'consumed unsupported edge')
            continue
        normal, support, radii, queries = raw['normal'], raw['support_points'], raw['query_radii_px'], raw['queries']
        require(finite(normal, (2,)) and math.hypot(*normal) > 0 and
            finite(support, (len(queries), 2)) and finite(radii, (len(queries),)) and
            min(radii) >= 0 and len(set(queries)) >= 3 and all(type(v) is int and 0 <= v < 84 and v//7 == edge for v in queries),
            'invalid original line support')
        audit.ok(edge in CAL, label + '.source_CAL_edge.' + str(edge), edge, CAL)
        for query, xy in zip(queries, support):
            audit.eq(obs['queries'][query]['calibrated_model_coverage'], True, label + '.query_CAL.' + str(query))
            audit.eq(obs['queries'][query]['selected_xy'], xy, label + '.sealed_support.' + str(query))
        length = math.hypot(*normal)
        n, offset = [v/length for v in normal], raw['offset']/length
        errors = [abs(dot(n, xy)-offset) for xy in support]
        good = math.isfinite(offset) and all(e <= r+1e-9 for e, r in zip(errors, radii))
        require(edge not in consumed or good, 'inconsistent consumed support line')
        if good and edge not in consumed:
            accepted.append(dict(edge=edge, normal=n, offset=offset, support_query_ids=queries))
    require(consumed <= set(seen), 'missing adopted supporting line')
    return sorted(accepted, key=lambda l: l['edge']), sorted(consumed)


def candidate(c, row, U, H, lines, audit, counts, label, scope):
    counts[scope + '_arithmetic_invocations'] += 1
    dims = dimensions(row['xyz']); d = c['dimension_index']
    require(type(d) is int and 0 <= d < len(dims), 'invalid returned candidate dimension')
    audit.eq(c['cf_extents'], dims[d], label + '.registered_dimensions')
    audit.eq(c['selected_hypothesis'], ('REGISTRY_WD', 'REGISTRY_DW')[d], label + '.dimension_name')
    audit.eq(c['fit_input_ids'], U, label + '.whole_fixed_U')
    audit.eq(c['fit_line_edges'], [l['edge'] for l in lines], label + '.whole_fixed_lines')
    audit.ok(not set(c['fit_input_ids']) & set(H), label + '.no_H_2D_fit')
    audit.eq(c['factor_pool_binding'], row['solver']['factor_pool_binding'], label + '.factor_binding_join')
    R, uv, J, depths = forward(dims[d], c['final_z'], row['K'])
    audit.near(c['R_cf'], R, label + '.independent_Rodrigues')
    audit.near(c['R_physical'], physical_rotation(R, d), label + '.physical_rotation')
    audit.near(c['centroid'], c['final_z'][3:], label + '.translation_join')
    audit.near(c['projected'], uv, label + '.independent_projection')
    audit.near(c['model_camera_depths_m'], depths, label + '.positive_depths')
    ranks, rr = geometry_witness(c['point_line_geometry'], uv, J, row['input_points'], U, lines, audit, label + '.geometry')
    audit.near(c['scalar_residuals_px'], rr, label + '.normalized_factor_residuals')
    pnorm = [math.dist(uv[k], row['input_points'][k]) for k in U]
    signed = [[dot(l['normal'], uv[k])-l['offset'] for k in EDGES[l['edge']]] for l in lines]
    lnorm = [math.sqrt(dot(values, values)/2) for values in signed]
    audit.near(c['residuals_used_px'], pnorm, label + '.point_norms')
    audit.near(c['line_endpoint_signed_residuals_px'], signed, label + '.line_endpoint_distances')
    audit.near(c['line_residual_RMS_px'], lnorm, label + '.one_edge_RMS')
    cost = 64*math.fsum(math.sqrt(1+(v/8)**2)-1 for v in rr)
    audit.near(c['soft_l1_cost'], cost, label + '.independent_whole_pool_soft_l1')
    audit.near(c['reported_soft_l1_cost'], cost, label + '.reported_optimizer_cost')
    audit.near(c['sse_px2'], dot(rr, rr), label + '.scalar_SSE')
    audit.near(c['factor_sse_px2'], dot(pnorm+lnorm, pnorm+lnorm), label + '.factor_SSE')
    audit.near(c['factor_truncated_sse_px2'], math.fsum(min(v*v, 64.) for v in pnorm+lnorm), label + '.diagnostic_truncated_SSE')
    # Exact membership recount uses the stored norms after independent near-check.
    ip = [k for k, v in zip(U, c['residuals_used_px']) if v <= 8.]
    il = [l['edge'] for l, v in zip(lines, c['line_residual_RMS_px']) if v <= 8.]
    audit.eq(c['final_inliers'], ip, label + '.point_inliers')
    audit.eq(c['final_line_inliers'], il, label + '.line_inliers')
    audit.eq(c['inlier_count'], len(ip), label + '.point_count')
    audit.eq(c['unique_line_inlier_count'], len(il), label + '.line_count')
    audit.eq(c['total_inlier_factor_count'], len(ip)+len(il), label + '.factor_count')
    audit.eq(c['diagnostic_inlier_scalar_residuals'], 2*(len(ip)+len(il)), label + '.inlier_scalar_count')
    subset = [l for l in lines if l['edge'] in il]
    if c['diagnostic_inlier_geometry'] is not None:
        ir, _ = geometry_witness(c['diagnostic_inlier_geometry'], uv, J, row['input_points'], ip, subset, audit, label + '.inlier_diagnostic')
        audit.eq(c['diagnostic_inlier_geometry_unavailable'], None, label + '.inlier_diagnostic_available')
        audit.eq(c['diagnostic_inlier_support_rank6'], ir['observed_normal_joint'] == ir['modeled_normal_joint'] == 6,
                 label + '.inlier_support_rank_record')
    else:
        audit.ok(isinstance(c['diagnostic_inlier_geometry_unavailable'], dict), label + '.typed_inlier_diagnostic_unavailable')
        audit.eq(c['diagnostic_inlier_support_rank6'], False, label + '.unavailable_inlier_rank')
    accepted = ranks['observed_normal_joint'] == ranks['modeled_normal_joint'] == 6
    audit.eq(c['accepted'], accepted, label + '.whole_pool_rank_acceptance')
    audit.eq(c['rejected'], None if accepted else 'FINAL_ACTUAL_FACTOR_RANK_BELOW_SIX', label + '.rank_rejection')
    for key, value in (('optimizer_success', True), ('local_only', True), ('global_uniqueness_proven', False),
                       ('initial_pose_residual_prior', False), ('inlier_geometry_is_acceptance_gate', False)):
        audit.eq(c[key], value, label + '.' + key)
    counts[scope + '_arithmetic_completed'] += 1
    return (c['soft_l1_cost'], d, c['start_index'])


def seed_valid(raw, dims):
    if not isinstance(raw, dict) or not raw.get('available'):
        return False
    if not all(finite(raw.get(k), shape) for k, shape in
               (('R_cf', (3, 3)), ('R_physical', (3, 3)), ('centroid', (3,)), ('cf_extents', (3,)))):
        return False
    for R in (raw['R_cf'], raw['R_physical']):
        determinant = dot(R[0], [R[1][1]*R[2][2]-R[1][2]*R[2][1],
            R[1][2]*R[2][0]-R[1][0]*R[2][2], R[1][0]*R[2][1]-R[1][1]*R[2][0]])
        if abs(determinant-1) > 1e-6 or max(abs(dot(a, b)-int(i == j)) for i, a in enumerate(R) for j, b in enumerate(R)) > 1e-6:
            return False
    matches = [i for i, d in enumerate(dims) if max(abs(a-b) for a, b in zip(raw['cf_extents'], d)) <= 1e-6]
    return len(matches) == 1 and max(abs(a-b) for row, other in zip(raw['R_physical'],
        physical_rotation(raw['R_cf'], matches[0])) for a, b in zip(row, other)) <= 1e-6


def packet(row, ledger, parent, obs, point, audit, counts, label):
    s, q, H, K, xyz = row['solver'], row['input_points'], row['hidden_initial'], row['K'], row['xyz']
    E = eligible(q, row['raw_hw']); U = [k for k in E if k not in H]
    dims = dimensions(xyz)
    counts['local_packets'] += 1
    audit.eq(row['method'], METHOD, label + '.fixed_method')
    audit.eq(row['head_arm'], 'IMAGE_ROLE', label + '.same_head')
    audit.eq(row['head_checkpoint_sha256'], CHECKPOINT, label + '.same_checkpoint')
    audit.eq(row['native_reference_id'], dict(id=row['id'], head_arm='IMAGE_ROLE'), label + '.native_reference_identity')
    audit.eq(row['parent_geometry_row_semantic_sha256'], semantic(parent), label + '.parent_row_binding')
    audit.eq(row['parent_observation_row_semantic_sha256'], semantic(obs), label + '.source_observation_binding')
    audit.eq(ledger['point_control_row_semantic_sha256'], semantic(point), label + '.same_point_control_binding')
    audit.eq(semantic(row['original_native_N3_points']), semantic(obs['native_N3_points']), label + '.original_N3')
    audit.eq(row['parent_native_N3_semantic_sha256'], semantic(obs['native_N3_points']), label + '.native_N3_hash')
    for key in ('id', 'session', 'K', 'xyz', 'raw_hw', 'selected_index', 'fixed_metadata', 'head_mode',
                'head_checkpoint_sha256', 'calibration_binding', 'input_points', 'observation_contract',
                'initial_pose', 'hidden_initial'):
        audit.eq(row[key], parent[key], label + '.immutable_parent.' + key)
    audit.eq(point['input_points'], q, label + '.same_q_for_point_control')
    audit.eq(point['hidden_initial'], H, label + '.same_H_for_point_control')
    audit.eq(obs['GT_input'], False, label + '.observation_GT_free')
    audit.eq(obs['initial_N3_pose'], row['initial_pose'], label + '.stored_initial_pose_join')
    audit.eq(obs['predicted_N3_hidden'], H, label + '.stored_original_H_join')
    for key, value in (('native_N3_is_numeric_final_pose_observation', False), ('missing_sparse_filled_for_numeric_fit', False),
        ('independent_PnP_or_PnL', False), ('final_numeric_pose_has_initial_prior', False), ('oracle', False),
        ('head_forward_calls', 0), ('calibration_or_decode_calls', 0), ('same_sparse_observation', True),
        ('initial_pose_may_supply_local_optimizer_start', True), ('full_candidate_and_operation_witnesses_preserved', True),
        ('solver_replay_latency_claim', False), ('reprojections_reused_as_observations', False)):
        audit.eq(row[key], value, label + '.row.' + key)
    for key in ('prior_used', 'initial_projection_used', 'initial_dimension_prior_used', 'known_dimension_constraint_used',
                'excluded_image_coordinates_used_for_scoring', 'excluded_image_coordinates_used_for_equivalence',
                'initial_pose_residual_prior', 'reprojected_points_reused_as_observations', 'same_edge_point_line_double_count',
                'global_uniqueness_proven', 'independent_PnP_or_PnL'):
        audit.eq(s[key], False, label + '.solver.' + key)
    for key in ('rank_is_local_only', 'no_minimum_point_inlier_gate', 'inlier_counts_are_diagnostic_only',
                'final_factor_pool_is_same_for_every_start', 'equivalence_uses_all_eight_model_predictions',
                'source_line_support_is_not_real_ownership_certificate', 'hidden_initial_excluded'):
        audit.eq(s[key], True, label + '.solver.' + key)
    audit.eq(s['derived_line_points'], 0, label + '.no_derived_points')
    audit.eq(s['solver'], 'LOCAL_POINT_LINE', label + '.LOCAL_backend')
    audit.eq(s['eligible'], E, label + '.eligible')
    audit.eq(s['used'], U, label + '.actual_U')
    audit.eq(s['hidden'], H, label + '.H')
    audit.eq(s['actual_self_hidden_ids'], H, label + '.H_alias')
    audit.eq(s['excluded'], H, label + '.excluded')
    audit.eq(s['temporary_excluded'], [], label + '.no_LOO_final_fit')
    audit.ok(not set(U) & set(H), label + '.H_fit_exclusion')
    adopted = row['observation_contract']['validated_boundary_corner_ids']
    lines, consumed = original_lines(obs, q, U, adopted, audit, label + '.physical_lines')
    edges = [l['edge'] for l in lines]
    audit.eq(s['line_edges'], edges, label + '.unused_original_lines')
    audit.eq(s['consumed_edges'], consumed, label + '.consumed_incident_edges')
    audit.eq(s['actual_adopted_boundary_ids'], [k for k in adopted if k in U], label + '.actual_adopted')
    pool = dict(point_ids=U, line_edges=edges, actual_point_factors=len(U), unique_line_factors=len(lines),
        scalar_residuals=2*(len(U)+len(lines)), line_support_queries=sum(len(l['support_query_ids']) for l in lines))
    audit.eq(s['factor_pool'], pool, label + '.factor_pool')
    ob = s['observation_binding']
    serialized = json.dumps(obs, sort_keys=True, separators=(',', ':'), allow_nan=True).encode()
    audit.eq(ob['sha256'], hashlib.sha256(serialized).hexdigest(), label + '.observation_semantic_SHA')
    audit.eq(ob['bytes'], len(serialized), label + '.observation_semantic_bytes')
    audit.eq(ledger['original_observation_binding'], ob, label + '.observation_binding_ledger')
    factor_binding = s['factor_pool_binding']
    audit.ok(isinstance(factor_binding, dict) and len(factor_binding['sha256']) == 64 and factor_binding['bytes'] > 0,
             label + '.factor_binding_shape')
    audit.eq(ledger['factor_pool_binding'], factor_binding, label + '.factor_binding_ledger')
    audit.eq(ledger['factor_pool'], pool, label + '.factor_pool_ledger')
    audit.eq(ledger['used_line_edges'], edges, label + '.line_ledger')
    audit.eq(ledger['consumed_edges'], consumed, label + '.consumed_ledger')
    audit.eq(ledger['original_line_edges'], [l['edge'] for l in obs['lines']], label + '.original_lines_ledger')
    audit.eq(ledger['coordinate_bank_count'], 1, label + '.one_bank')
    audit.eq(ledger['logical_pose_paths'], 1, label + '.one_local_path')
    audit.eq(ledger['parent_packet_semantic_sha256'], semantic(dict(parent_row=parent,
        native_N3_points=obs['native_N3_points'], parent_completion=row['parent_completion'], role_observation=obs)),
        label + '.parent_packet_ledger_binding')
    for key in ('PnP_calls', 'detector_calls', 'N3_calls', 'head_calls', 'initial_pose_calls',
                'calibration_calls', 'query_decode_calls', 'new_training_updates', 'new_RGB'):
        audit.eq(ledger[key], 0, label + '.ledger.' + key)
    op = s['operation_counts']
    audit.eq(set(op), set(LOCAL_KEYS), label + '.exact_local_counter_keys')
    require(all(type(v) is int and v >= 0 for v in op.values()), 'invalid local counters')
    audit.eq(op['local_solve_calls'], 1, label + '.one_actual_local_entry')
    audit.eq(s['local_bank_counts'], op, label + '.fresh_bank_deltas')
    audit.eq(ledger['local_operation_counts'], op, label + '.ledger_local_counts')
    audit.eq(ledger['local_bank_counts'], op, label + '.ledger_bank_counts')
    audit.ok(all(v == 0 for v in s['hypothesis_bank_counts'].values()), label + '.no_finite_PnP_bank_calls')
    bank = ledger['coordinate_banks']
    audit.eq(len(bank), 1, label + '.one_coordinate_bank_record')
    audit.eq(bank[0]['input_hash'], s['input_hash'], label + '.bank_hash_join')
    audit.ok(all(v == 0 for k, v in bank[0].items() if k != 'input_hash'), label + '.bank_no_hidden_PnP_calls')
    attempts, records = s['optimizer_attempts'], s['all_candidate_solutions']
    audit.eq(s['candidate_count'], len(records), label + '.stored_candidate_count')
    audit.eq(op['local_start_entries'], len(attempts), label + '.start_entry_count')
    audit.eq(op['seed_Rodrigues_calls'], len(attempts), label + '.start_remap_rotation_entries')
    actual = [e for e in attempts if e['actual_optimizer_called']]
    reused = [e for e in attempts if e['cache_reused']]
    audit.eq(op['local_optimizer_calls'], len(actual), label + '.actual_optimizer_dispatch_count')
    audit.eq(s['refit_count'], len(actual), label + '.optimizer_entries_refit_count')
    audit.eq(op['local_start_cache_hits'], len(reused), label + '.cache_hit_count')
    audit.eq(op['local_optimizer_completions'], sum('reported_soft_l1_cost' in e for e in actual), label + '.optimizer_return_count')
    audit.eq(op['candidate_validation_calls'], op['local_optimizer_completions'], label + '.returned_fit_validation_entries')
    audit.eq(op['candidate_Rodrigues_calls'], len(records), label + '.candidate_R_entries')
    audit.eq(op['optimizer_projectPoints_calls'], op['optimizer_residual_calls']+op['optimizer_jacobian_calls'], label + '.callback_projection_entries')
    audit.eq(s['initial_pose_used'], bool(attempts), label + '.initial_start_flag')
    audit.eq(s['initial_pose_start_used'], bool(attempts), label + '.initial_start_alias')
    sources = s['start_source_witnesses']
    has_factors = pool['scalar_residuals'] >= 6
    audit.eq(op['start_sources_examined'], 2 if has_factors else 0, label + '.two_existing_sources_examined')
    expected_sources = [('SEALED_INITIAL_N3', parent['initial_pose']), ('SEALED_AVAILABLE_POINT_ONLY', parent['solver'])] if has_factors else []
    audit.eq(len(sources), len(expected_sources), label + '.source_witness_count')
    accepted_sources = []
    for witness, (name, raw) in zip(sources, expected_sources):
        audit.eq(witness['source'], name, label + '.source_name.' + name)
        audit.eq(witness['original_pose'], raw, label + '.sealed_start_pose.' + name)
        valid = seed_valid(raw, dims)
        audit.eq(witness['accepted'], valid, label + '.seed_validity.' + name)
        if valid:
            accepted_sources.append((name, raw))
            audit.eq(witness['residual_prior'], False, label + '.no_seed_residual.' + name)
            audit.eq(witness['pose_as_observation'], False, label + '.no_pose_observation.' + name)
            audit.eq(witness['all_registry_dimensions_will_be_tried'], True, label + '.all_dimensions.' + name)
    audit.eq(len(attempts), len(accepted_sources)*len(dims), label + '.all_available_sources_all_dimensions')
    cache = {}
    for i, entry in enumerate(attempts):
        name, raw = accepted_sources[i//len(dims)]
        d = i % len(dims)
        audit.eq(entry['start_index'], i, label + '.start_index.' + str(i))
        audit.eq(entry['source'], name, label + '.start_source.' + str(i))
        audit.eq(entry['dimension_index'], d, label + '.start_dimension.' + str(i))
        audit.eq(entry['fit_point_ids'], U, label + '.start_whole_U.' + str(i))
        audit.eq(entry['fit_line_edges'], edges, label + '.start_whole_lines.' + str(i))
        audit.eq(entry['factor_pool_binding'], factor_binding, label + '.start_factor_binding.' + str(i))
        audit.eq(entry['initial_pose_residual_prior'], False, label + '.start_no_prior.' + str(i))
        R0, _ = rotation_and_right_J(entry['initial_z'][:3])
        audit.near(physical_rotation(R0, d), raw['R_physical'], label + '.remapped_same_physical_R.' + str(i))
        audit.near(entry['initial_z'][3:], raw['centroid'], label + '.same_seed_translation.' + str(i))
        key = (d, b''.join(struct.pack('<d', v) for v in entry['initial_z']))
        audit.eq(entry['cache_reused'], key in cache, label + '.exact_start_cache.' + str(i))
        if key in cache:
            audit.eq(entry['actual_optimizer_called'], False, label + '.cache_no_new_optimizer.' + str(i))
            audit.eq(entry['cache_source_start_index'], cache[key], label + '.cache_source.' + str(i))
        else:
            cache[key] = i
            audit.eq(entry['actual_optimizer_called'], True, label + '.start_optimizer_not_initial_rank_veto.' + str(i))
        if entry.get('initial_geometry') is not None:
            _, puv, pJ, _ = forward(dims[d], entry['initial_z'], K)
            geometry_witness(entry['initial_geometry'], puv, pJ, q, U, lines, audit, label + '.initial_geometry.' + str(i))
        else:
            audit.ok(isinstance(entry.get('initial_geometry_unavailable'), dict), label + '.typed_initial_diagnostic_failure.' + str(i))
        if 'candidate_index' in entry:
            ci = entry['candidate_index']
            require(type(ci) is int and 0 <= ci < len(records), 'invalid returned candidate index')
            audit.eq(entry['final_z'], records[ci]['final_z'], label + '.attempt_return_candidate_join.' + str(i))
            audit.eq(entry['accepted'], records[ci]['accepted'], label + '.attempt_acceptance_join.' + str(i))
    if attempts:
        audit.eq(s['local_start_cache'], dict(unique_numeric_starts=len(cache), logical_start_entries=len(attempts), reuse_count=len(reused)),
                 label + '.whole_cache_ledger')
    ranked = []
    for i, c in enumerate(records):
        audit.eq(c['candidate_index'], i, label + '.contiguous_candidate_index.' + str(i))
        require(type(c['start_index']) is int and 0 <= c['start_index'] < len(attempts), 'invalid candidate start index')
        audit.eq(attempts[c['start_index']]['actual_optimizer_called'], True, label + '.unique_candidate_actual_optimizer.' + str(i))
        key = candidate(c, row, U, H, lines, audit, counts, label + '.candidate.' + str(i), 'stored_candidate')
        if c['accepted']:
            ranked.append((key, c))
    ranked.sort(key=lambda pair: pair[0])
    if attempts:
        audit.eq(s['viable_candidate_count'], len(ranked), label + '.viable_returned_count')
    if ranked:
        best = ranked[0][1]
        audit.eq(s['best_candidate'], best, label + '.whole_pool_softcost_selection')
        expected_per_dim = [next(c for _, c in ranked if c['dimension_index'] == d) for d in range(len(dims))
                            if any(c['dimension_index'] == d for _, c in ranked)]
        audit.eq(s['per_dimension_best'], expected_per_dim, label + '.all_dimension_minima')
        audit.eq(len(s['alternatives']), len(ranked)-1, label + '.all_ranked_alternatives')
        ambiguous, duplicates, ties, multiple = False, 0, 0, False
        for (_, c), stored in zip(ranked[1:], s['alternatives']):
            same = equivalent(best, c, xyz); delta = c['soft_l1_cost']-best['soft_l1_cost']; tied = abs(delta) <= TIE
            expected = dict(c, numerically_equivalent_to_selected=same, numerical_objective_tie=tied,
                            objective_difference_from_selected_px2=delta)
            audit.near(stored, expected, label + '.alternative.' + str(c['candidate_index']))
            duplicates += int(same); ties += int(tied); multiple |= not same; ambiguous |= not same and tied
        audit.eq(s['numerical_duplicate_solution_count'], duplicates, label + '.duplicate_count')
        audit.eq(s['numerical_tied_solution_count'], ties, label + '.tie_count')
        audit.eq(s['multiple_solutions'], multiple, label + '.distinct_solutions')
        audit.eq(s['unresolved_ambiguity'], ambiguous, label + '.distinct_tied_local_ambiguity')
        audit.eq(s['available'], not ambiguous, label + '.availability_after_ambiguity')
        audit.eq(s['state'], 'AMBIGUOUS_LOCAL_POINT_LINE' if ambiguous else 'NEW_POSE', label + '.local_result_status')
    else:
        audit.eq(s['available'], False, label + '.no_viable_no_NEW')
        if not has_factors:
            audit.eq(s['state'], 'INSUFFICIENT_LOCAL_FACTORS', label + '.insufficient_scalar_status')
        elif not accepted_sources:
            audit.eq(s['state'], 'NO_LOCAL_INITIALIZATION', label + '.no_seed_status')
        else:
            audit.ok(s['state'] in ('NUMERICAL_RANK_DEFICIENT', 'LOCAL_NUMERICAL_FAILURE'), label + '.typed_numeric_or_rank_failure')
    new = bool(s['available']); fallback = not new and bool(row['initial_pose'].get('available'))
    available = new or fallback
    audit.eq(row['new_pose_estimated'], new, label + '.driver_new')
    audit.eq(row['fallback_used'], fallback, label + '.driver_fallback')
    audit.eq(row['pose_available'], available, label + '.driver_available')
    audit.eq(row['no_pose'], not available, label + '.driver_no_pose')
    audit.eq(row['output_status'], 'NEW_POSE' if new else 'N3_BASELINE_FALLBACK' if fallback else 'POSE_FAILURE', label + '.driver_status')
    native = obs['native_N3_points']; displayed = [list(xy) for xy in native]
    sparse = [list(xy) for xy in q]
    if new:
        chosen = s['best_candidate']
        candidate(chosen, row, U, H, lines, audit, counts, label + '.chosen_recheck', 'chosen_recheck')
        audit.eq(s['fit_input_ids'], U, label + '.accepted_whole_U')
        audit.eq(s['fit_line_edges'], edges, label + '.accepted_whole_lines')
        for key in ('R_cf', 'R_physical', 'centroid', 'cf_extents', 'projected', 'point_line_geometry',
            'diagnostic_inlier_geometry', 'diagnostic_inlier_geometry_unavailable', 'diagnostic_inlier_support_rank6',
            'diagnostic_inlier_scalar_residuals', 'final_inliers', 'final_line_inliers', 'soft_l1_cost', 'sse_px2'):
            audit.near(s[key], chosen[key], label + '.selected_top_level_join.' + key)
        for key in ('R_cf', 'R_physical', 'centroid', 'cf_extents', 'projected'):
            audit.near(row['actual_pose'][key], s[key], label + '.driver_actual_Rt_join.' + key)
        audit.eq(row['actual_pose']['available'], True, label + '.actual_pose_NEW_available')
        audit.eq(row['stored_jacobian_fit_ids'], U, label + '.stored_J_fit_ids')
        audit.eq(row['stored_jacobian_fit_line_edges'], edges, label + '.stored_J_fit_lines')
        audit.eq(s['fit_has_fewer_than_four_actual_points'], len(U) < 4, label + '.fewer4_numeric_only')
        for k in range(8):
            if k not in H and finite(q[k], (2,)) and q[k] != [-1, -1]:
                displayed[k] = q[k]
        for k in H:
            displayed[k] = s['projected'][k]; sparse[k] = s['projected'][k]
        audit.eq(op['hidden_reprojection_assignments'], len(H), label + '.H_only_after_NEW')
    else:
        audit.eq(row['actual_pose'], row['initial_pose'], label + '.fallback_actual_pose_full_initial')
        audit.eq(op['hidden_reprojection_assignments'], 0, label + '.unavailable_no_H_projection')
        audit.eq(row['stored_jacobian_fit_ids'], [], label + '.unavailable_no_final_J_support')
        audit.eq(row['stored_jacobian_fit_line_edges'], [], label + '.unavailable_no_final_J_lines')
    audit.near(s['points_final'], sparse, label + '.solver_sparse_output_only_H_replaced')
    audit.near(row['native_points'], displayed, label + '.display_new_or_full_fallback')
    audit.eq(row['native_points'][8], native[8], label + '.detector_center_preserved')
    audit.eq(row['reprojected_ids'], H if new else [], label + '.driver_H_reprojection_ids')
    audit.eq(row['hidden_reprojected'], new and bool(H), label + '.driver_H_reprojection_flag')
    audit.eq(s['hidden_reprojected'], new and bool(H), label + '.solver_H_reprojection_flag')
    counts['state:' + s['state']] += 1
    counts['output:' + row['output_status']] += 1
    counts['actual_points:' + str(len(U))] += 1
    counts['unused_lines:' + str(len(lines))] += 1
    counts['expected_actual_Rodrigues_entries'] += (len(attempts)+len(records)+
        sum(bool(e['success']) and finite(e.get('final_z'), (6,)) for e in actual)+2*max(len(ranked)-1, 0))
    if new and len(U) < 4 and lines:
        counts['new_under4_with_actual_unused_lines'] += 1
    if new and not lines:
        counts['new_point_LOCAL_no_unused_lines'] += 1
    if new and not s['diagnostic_inlier_support_rank6']:
        counts['new_whole_pool_rank6_but_inlier_diagnostic_rank_insufficient'] += 1
    for k, v in op.items():
        counts['local:' + k] += v


def input_paths(args):
    folder, parent, point = args.input.resolve(), args.parent.resolve(), args.point_parent.resolve()
    paths = dict(geometry=folder/'GEOMETRY_SEALED.jsonl.gz', ledgers=folder/'CONTROL_LEDGERS.jsonl.gz',
        accuracy_protocol=args.protocol.resolve(), geometry_seal=folder/'GEOMETRY_SEAL.json',
        control_receipt=folder/'CONTROL_RECEIPT.json', parent_population_checks=folder/'PARENT_POPULATION_CHECKS.json',
        control_started=folder/'CONTROL_STARTED.json', preflight=folder/'PREFLIGHT.json',
        checker=Path(__file__).resolve(), solver=CODE/'solver.py', pipeline=CODE/'pipeline.py',
        runner=CODE/'runner.py', common=CODE/'common.py', cohort=args.cohort.resolve(),
        v4_pose=REPO/'scripts/research/pallet_cornerwise_independent_20261010_v4/pose.py',
        v5_line_solver=REPO/'scripts/research/pallet_partial_line_independent_20261010_v5/solver.py',
        v1_solver=REPO/'scripts/research/pallet_observation_refiner_20261009_v1/solver.py',
        v2_assemble=REPO/'scripts/research/pallet_boundary_corner_refiner_20261010_v2/pipeline.py')
    for name in ('PROTOCOL.json', 'GEOMETRY_SEAL.json', 'INFERENCE_RECEIPT.json',
                 'GEOMETRY_SEALED.jsonl.gz', 'OBSERVATIONS.jsonl.gz', 'FIXED_GEOMETRY_SEALED.jsonl.gz', 'BASE_N3_PARITY.json'):
        paths['parent:' + name] = parent/name
    for name in ('PROTOCOL.json', 'GEOMETRY_SEAL.json', 'CONTROL_RECEIPT.json', 'GEOMETRY_SEALED.jsonl.gz',
                 'CONTROL_LEDGERS.jsonl.gz', 'PARENT_POPULATION_CHECKS.json', 'VALIDATION_PROTOCOL.json', 'VALIDATION_CHECKS.json'):
        paths['point:' + name] = point/name
    receipt = read(paths['control_receipt'])
    for i, _ in enumerate(receipt['resource_snapshots']):
        paths['resource:%03d' % i] = folder/('RESOURCE_%03d.json' % i)
    core = read(paths['accuracy_protocol'])
    for key, expected in core['inputs'].items():
        if key.startswith('cpu_'):
            stored = Path(expected['path'])
            candidate_path = stored if stored.is_absolute() else REPO/stored
            require(candidate_path.is_file(), 'CPU authority requires a resolvable public/absolute byte-bound path:' + key)
            paths[key] = candidate_path
    return paths


def core_bindings(inputs, core):
    keys = dict(checker='validation_checks.py', solver='solver.py', pipeline='pipeline.py',
        runner='runner.py', common='common.py', v4_pose='v4_pose', v5_line_solver='v5_line_solver',
        v1_solver='v1_solver', v2_assemble='v2_assemble', cohort='cohort')
    keys.update({k: k for k in inputs if k.startswith(('parent:', 'point:'))})
    keys.update({k: k for k in inputs if k.startswith('cpu_')})
    for key, source_key in keys.items():
        require(same_binding(inputs[key], core['inputs'][source_key]), 'accuracy core byte binding differs: ' + key)


def guard(args, stage):
    for path in (args.input, args.output, args.protocol, args.parent, args.point_parent, args.cohort):
        path = path.absolute()
        require(not any(p.is_symlink() for p in (path, *path.parents)), 'symlink input/output ancestry')
    output = args.output.resolve()
    require(output == DOC.resolve() or output.is_relative_to(PRIVATE.resolve()), 'only new V9 DOC/private audit output')
    require(all(path.is_dir() for path in (args.input, args.output, args.parent, args.point_parent)), 'existing directories required')
    for name in OUTPUTS if stage == 'freeze' else OUTPUTS[1:]:
        require(not (output/name).exists(), 'preserve existing ' + name)
    if stage == 'run':
        require((output/OUTPUTS[0]).is_file(), 'own freeze required before arithmetic')
    return args.input.resolve(), output


def bound_receipts(paths, inputs):
    core, seal, receipt, population = [read(paths[k]) for k in
        ('accuracy_protocol', 'geometry_seal', 'control_receipt', 'parent_population_checks')]
    require(core['schema'] == 'fixed_same_observation_local_C2_protocol_v9' and
        core['methods'] == [METHOD] and core['frames'] == core['rows'] == 245, 'fixed original C2 protocol differs')
    require(seal['schema'] == 'fixed_sparse_local_line_geometry_seal_v9' and seal['complete'] is True and
        seal['GT_read_allowed'] is False and seal['frames'] == seal['rows'] == seal['ledger_rows'] == 245,
        'complete GT-free245 geometry/ledger seal required')
    require(receipt['schema'] == 'fixed_sparse_local_line_control_receipt_v9' and
        receipt['complete'] is True and receipt['error'] is None and receipt['cleanup_error'] is None,
        'completed local controls with successful cleanup required')
    require(population['complete'] is True and population['passed'] is True and population['frames'] == 245,
        'complete GT-free parent population proof required')
    core_bindings(inputs, core)
    for seal_key, key in (('protocol', 'accuracy_protocol'), ('geometry', 'geometry'), ('ledgers', 'ledgers'),
                         ('control_receipt', 'control_receipt'), ('parent_population_checks', 'parent_population_checks')):
        require(same_binding(seal[seal_key], inputs[key]), 'local seal binding differs: ' + key)
    require(same_binding(receipt['protocol'], inputs['accuracy_protocol']), 'local receipt protocol differs')
    require(same_binding(population['point_completion']['geometry'], inputs['point:GEOMETRY_SEALED.jsonl.gz']),
            'parent proof point comparator bytes differ')
    require(same_binding(core['parent_population_checks'], inputs['parent_population_checks']), 'core parent proof bytes differ')
    joined = read(paths['cpu_success'])
    require(joined['schema'] == 'sparse_local_line_joined_CPU_contract_checks_v9' and joined['complete'] is True and
        joined['passed'] is True and joined['contract_groups'] == 14 and
        joined['original_attempt_passed_groups'] == joined['accepted_original_unchanged_groups'] == 12 and
        joined['review_targeted_tests'] == joined['accepted_review_corrected_groups'] == 2 and
        joined['original_attempt_reported_passed'] is False and joined['other_twelve_rerun'] is False and
        joined['solver_or_threshold_changed'] is False and joined['original_attempt_preserved_unchanged'] is True,
        'actual joined original12+review2 CPU authority differs')
    require(same_binding(core['CPU_authority']['joined_success_authority'], inputs['cpu_success']), 'core CPU success authority differs')
    for key, source in (('original_protocol', 'cpu_protocol'), ('original_receipt', 'cpu_original'),
        ('original_started', 'cpu_original_started'), ('review_protocol', 'cpu_review_protocol'),
        ('review_receipt', 'cpu_review_success'), ('review_started', 'cpu_review_success_started')):
        require(same_binding(joined[key], inputs[source]), 'joined CPU evidence byte binding differs:' + key)
    for expected in joined['code'].values():
        require(same_binding(binding(REPO/expected['path']), expected), 'CPU-tested frozen source differs')
    parent_seal, parent_receipt = read(paths['parent:GEOMETRY_SEAL.json']), read(paths['parent:INFERENCE_RECEIPT.json'])
    require(parent_seal['complete'] is True and parent_seal['GT_read_allowed'] is False and parent_seal['frames'] == 245 and
        parent_seal['rows'] == 1960 and parent_seal['fixed_rows'] == 490, 'complete same V7 parent required')
    require(parent_receipt['complete'] is True and parent_receipt['cleanup_error'] is None and
        parent_receipt['inference_error'] is None, 'V7 parent cleanup incomplete')
    for key, name in (('protocol', 'PROTOCOL.json'), ('geometry', 'GEOMETRY_SEALED.jsonl.gz'),
                      ('observations', 'OBSERVATIONS.jsonl.gz'), ('fixed_geometry', 'FIXED_GEOMETRY_SEALED.jsonl.gz'),
                      ('parity', 'BASE_N3_PARITY.json')):
        require(same_binding(parent_seal[key], inputs['parent:' + name]), 'V7 parent seal binding differs:' + name)
    point_seal, point_receipt = read(paths['point:GEOMETRY_SEAL.json']), read(paths['point:CONTROL_RECEIPT.json'])
    require(point_seal['complete'] is True and point_seal['GT_read_allowed'] is False and
        point_seal['frames'] == 245 and point_seal['rows'] == 735 and point_seal['ledger_rows'] == 245,
        'complete same V8 point comparator required')
    require(point_receipt['complete'] is True and point_receipt['cleanup_error'] is None and point_receipt['error'] is None,
        'V8 comparator cleanup incomplete')
    for key, name in (('protocol', 'PROTOCOL.json'), ('geometry', 'GEOMETRY_SEALED.jsonl.gz'), ('ledgers', 'CONTROL_LEDGERS.jsonl.gz'),
                      ('control_receipt', 'CONTROL_RECEIPT.json'), ('parent_population_checks', 'PARENT_POPULATION_CHECKS.json')):
        require(same_binding(point_seal[key], inputs['point:' + name]), 'V8 comparator seal binding differs:' + name)
    point_validation = read(paths['point:VALIDATION_CHECKS.json'])
    require(point_validation['complete'] is True and point_validation['passed'] is True, 'V8 independent validation failed')
    for name in ('GEOMETRY_SEAL.json', 'GEOMETRY_SEALED.jsonl.gz', 'CONTROL_LEDGERS.jsonl.gz', 'CONTROL_RECEIPT.json'):
        require(same_binding(point_validation['inputs'][name], inputs['point:' + name]), 'V8 checked bytes differ:' + name)
    return core, seal, receipt, population


def freeze(args):
    _, output = guard(args, 'freeze')
    paths = input_paths(args); inputs = {k: binding(p) for k, p in paths.items()}
    bound_receipts(paths, inputs)
    write_new(output/OUTPUTS[0], dict(schema='supplemental_sparse_local_point_line_scalar_protocol_v9',
        checker=inputs['checker'], inputs=inputs, methods=[METHOD], frames=245, rows=245, ledger_rows=245,
        limits=LIMITS, scalar_absolute_tolerance=ATOL, scalar_relative_tolerance=RTOL,
        rank_relative_threshold=RANK, objective_tie_px2=TIE,
        frozen_after_complete_GT_free_geometry_and_before_own_arithmetic=True))
    print('SPARSE_LOCAL_SCALAR_FROZEN', binding(output/OUTPUTS[0])['sha256'], flush=True)


def population_stream(path, field, names, primary, total, cohort, audit, label):
    seen, counts = set(), Counter()
    for row in rows(path):
        key = (row[field], row['id'])
        require(row[field] in names and row['id'] in cohort and key not in seen, label + ': unknown/duplicate population row')
        audit.ok(not TRUTH.intersection(row), label + '.GT_free.' + row[field])
        seen.add(key); counts[row[field]] += 1
        if row[field] == primary:
            yield row
    audit.eq(len(seen), total, label + '.full_population_count')
    for name in names:
        audit.eq(counts[name], 245, label + '.per_method245.' + name)
        audit.eq({fid for method, fid in seen if method == name}, cohort, label + '.same_cohort.' + name)


def fixed_population(path, cohort, audit):
    seen, counts = set(), Counter()
    for row in rows(path):
        key = (row['method'], row['id'])
        require(row['method'] in ('BASE', 'N3_SUBPIX') and row['id'] in cohort and key not in seen, 'unknown fixed parent population')
        audit.ok(not TRUTH.intersection(row), 'fixed_parent.GT_free')
        seen.add(key); counts[row['method']] += 1
    audit.eq(len(seen), 490, 'fixed_parent.complete490')
    audit.eq(dict(counts), dict(BASE=245, N3_SUBPIX=245), 'fixed_parent.each245')


def recorded_receipts(paths, inputs, core, seal, receipt, population, counts, audit):
    audit.eq(seal['cleanup_completed_before_seal'], True, 'local.cleanup_before_seal')
    audit.eq(seal['no_scored_or_human_inputs'], True, 'local.no_scored_fitting')
    audit.eq(seal['latency_benchmark'], False, 'local.not_latency')
    audit.eq(receipt['environment_and_monkeypatch_cleanup_completed'], True, 'local.context_cleanup_complete')
    audit.eq(receipt['actual_optimizer_dispatch_count_join'], True, 'local.recorded_actual_dispatch_count_join')
    for key in ('GT_access_during_controls', 'runtime_benchmark', 'deployment_latency_claim'):
        audit.eq(receipt[key], False, 'local.receipt.' + key)
    for key in ('actual_detector_calls', 'actual_N3_calls', 'actual_head_calls', 'actual_initial_pose_calls',
                'actual_CAL_calls', 'actual_query_decode_calls', 'actual_model_constructors', 'new_training_updates', 'new_RGB'):
        audit.eq(receipt[key], 0, 'local.receipt.' + key)
    audit.eq(receipt['source_asset_or_GT_attempted_reads'], [], 'local.no_forbidden_asset_reads')
    actual = receipt['actual_counts']
    for key in ('coordinate_banks_started', 'coordinate_banks_complete', 'logical_local_pose_paths_started',
                'logical_local_pose_paths_complete', 'geometry_rows', 'ledger_rows', 'frames_complete'):
        audit.eq(actual[key], 245, 'local.recorded.' + key)
    for receipt_key, local_key in (('actual_SciPy_least_squares_entries', 'local_optimizer_calls'),
        ('actual_SciPy_least_squares_returns', 'local_optimizer_completions'),
        ('actual_optimizer_residual_entries', 'optimizer_residual_calls'), ('actual_optimizer_jacobian_entries', 'optimizer_jacobian_calls')):
        audit.eq(actual[receipt_key], counts['local:' + local_key], 'local.actual_vs_all_rows.' + receipt_key)
    audit.eq(actual.get('actual_SciPy_least_squares_exceptions', 0),
        actual.get('actual_SciPy_least_squares_entries', 0)-actual.get('actual_SciPy_least_squares_returns', 0), 'local.actual_optimizer_exceptions')
    audit.eq(receipt['local_operation_counts'], {k: counts['local:' + k] for k in LOCAL_KEYS}, 'local.whole_ledger_counter_sum')
    primitive = receipt['actual_OpenCV_entry_calls']
    audit.ok(not set(primitive)-set(PRIMITIVES), 'local.known_actual_primitive_fields')
    require(all(type(v) is int and v >= 0 for v in primitive.values()), 'invalid actual primitive counts')
    for key in ('solvePnP', 'solvePnPGeneric', 'solvePnPRefineLM', 'cornerSubPix'):
        audit.eq(primitive.get(key, 0), 0, 'local.no_new_PnP_or_subpix.' + key)
    audit.eq(primitive.get('projectPoints', 0), counts['local:optimizer_projectPoints_calls']+
        counts['local:diagnostic_projectPoints_calls'], 'local.actual_all_projection_entries')
    audit.eq(primitive.get('Rodrigues', 0), counts['expected_actual_Rodrigues_entries'],
             'local.actual_remap_valid_candidate_and_equivalence_rotation_entries')
    audit.ok(same_binding(receipt['actual_entry_counter_code'], inputs['runner']), 'local.actual_entry_counter_code_binding')
    audit.eq(receipt['actual_OpenCV_primitive_names'], list(PRIMITIVES), 'local.actual_primitive_name_scope')
    audit.eq(receipt['actual_counter_scope'],
        'full local packet including optimizer/callbacks, diagnostics, equivalence and final display', 'local.actual_counter_scope')
    environment = receipt['library_environment']
    audit.eq(environment['solve_OpenCV_threads'], 1, 'local.recorded_OpenCV_threads')
    audit.eq(environment['Torch_or_model_library_initialized'], False, 'local.recorded_no_model_library')
    audit.eq(set(environment['thread_environment']), {'OMP_NUM_THREADS', 'OPENBLAS_NUM_THREADS', 'MKL_NUM_THREADS'},
             'local.recorded_thread_environment')
    for key in ('python', 'numpy', 'scipy', 'opencv'):
        audit.ok(isinstance(environment[key], str) and bool(environment[key]), 'local.recorded_library.' + key)
    audit.eq(receipt['serialization']['diagnostic_fields_removed'], 0, 'local.full_witness_preserved')
    audit.eq(receipt['serialization']['full_parent_population_retained'], False, 'local.no_population_witness_retention')
    for name in ('geometry', 'ledgers'):
        s = receipt['serialization']['streams'][name]
        audit.eq(s['rows'], 245, 'local.stream245.' + name)
        audit.eq(s['published'], True, 'local.stream_published.' + name)
        audit.eq(s['close_errors'], [], 'local.stream_closed.' + name)
        audit.eq(s['interruption_preservation_errors'], [], 'local.no_preservation_error.' + name)
    audit.eq(receipt['protection_before'], receipt['protection_after'], 'local.recorded_protection_unchanged')
    for key in ('passed', 'source_checkout_unchanged'):
        audit.eq(receipt['protection_after'][key], True, 'local.recorded_protection.' + key)
    audit.eq(receipt['protection_after']['changed_protected_paths'], [], 'local.recorded_no_protected_changes')
    audit.eq(population['full_population_checked_before_first_local_optimizer'], True, 'local.parent_checked_before_optimizer')
    audit.eq(population['GT_or_scored_inputs_decoded'], False, 'local.parent_no_GT_or_scored_decode')
    audit.eq(population['full_parent_population_rows_retained'], 0, 'local.parent_no_full_witness_retention')
    audit.eq(population['one_frame_primary_ROLE_and_point_control_kept'], True, 'local.parent_one_frame_retention')
    audit.eq(population['completion'], core['parent_completion'], 'local.parent_completion_protocol_join')
    audit.eq(seal['parent_completion'], core['parent_completion'], 'local.parent_completion_seal_join')
    audit.eq(seal['point_completion'], core['point_completion'], 'local.point_completion_seal_join')
    started = read(paths['control_started'])
    audit.ok(same_binding(started['protocol'], inputs['accuracy_protocol']), 'local.started_protocol_binding')
    for i, declared in enumerate(receipt['resource_snapshots']):
        path = paths['resource:%03d' % i]
        snapshot = read(path)
        audit.eq(snapshot, declared, 'local.recorded_resource_snapshot_identity.' + str(i))
        audit.ok(same_binding(binding(path), inputs['resource:%03d' % i]), 'local.recorded_resource_bytes.' + str(i))
        audit.eq(snapshot['quiet'], True, 'local.recorded_quiet_snapshot.' + str(i))
        audit.eq(snapshot['temperature_under_80'], True, 'local.recorded_thermal_snapshot.' + str(i))
    audit.eq(receipt['no_automatic_retry'], True, 'local.no_automatic_retry')


def run(args):
    _, output = guard(args, 'run')
    paths = input_paths(args); own_path = output/OUTPUTS[0]
    own = read(own_path); own_binding = binding(own_path)
    inputs = {k: binding(p) for k, p in paths.items()}
    require(own['schema'] == 'supplemental_sparse_local_point_line_scalar_protocol_v9' and
        own['inputs'] == inputs and own['checker'] == inputs['checker'] and own['methods'] == [METHOD] and
        own['frames'] == own['rows'] == own['ledger_rows'] == 245 and own['limits'] == LIMITS and
        own['scalar_absolute_tolerance'] == ATOL and own['scalar_relative_tolerance'] == RTOL and
        own['rank_relative_threshold'] == RANK and own['objective_tie_px2'] == TIE, 'own frozen protocol differs before arithmetic')
    core, seal, receipt, population = bound_receipts(paths, inputs)
    write_new(output/OUTPUTS[1], dict(schema='supplemental_sparse_local_point_line_scalar_started_v9',
        own_protocol=own_binding, inputs=inputs, checker=inputs['checker'], new_production_calls=0,
        GT_image_model_optimizer_calls=0, automatic_retry=False))
    audit, counts, failure = Audit(), Counter(), None
    began = time.monotonic()
    try:
        cohort = read(paths['cohort'])
        audit.eq(cohort['counts'], dict(clean=153, moderate=92, severe_excluded=74, original=319), 'cohort.easy_moderate_only')
        ordered, known = cohort['ids'], set(cohort['ids'])
        require(len(ordered) == len(known) == 245 and [f['id'] for f in cohort['frames']] == ordered, 'cohort order/population differs')
        audit.ok(all(f['label'] in ('clean', 'moderate') for f in cohort['frames']), 'cohort.no_severe')
        audit.ok(not known & set(cohort['excluded_ids']) and len(set(cohort['excluded_ids'])) == 74, 'cohort.excluded74')
        parent = iter(population_stream(paths['parent:GEOMETRY_SEALED.jsonl.gz'], 'method', PARENT_METHODS,
            'IMAGE_ROLE_BOUNDARY_ONLY', 1960, known, audit, 'parent_geometry'))
        obs = iter(population_stream(paths['parent:OBSERVATIONS.jsonl.gz'], 'head_arm', HEADS, 'IMAGE_ROLE', 735, known, audit, 'parent_observation'))
        point = iter(population_stream(paths['point:GEOMETRY_SEALED.jsonl.gz'], 'method', POINT_METHODS, POINT_METHODS[0], 735, known, audit, 'point_controls'))
        new, ledgers = iter(rows(paths['geometry'])), iter(rows(paths['ledgers']))
        for i, frame_id in enumerate(ordered):
            group = [next(stream, None) for stream in (new, ledgers, parent, obs, point)]
            require(all(isinstance(row, dict) for row in group), 'incomplete joined frame group')
            row, ledger, p, o, control = group
            require(all(r['id'] == frame_id and r['session'] == p['session'] for r in group), 'joined frame order/session differs')
            audit.eq(row['session'], cohort['frames'][i]['session'], 'cohort.frame_session.' + str(i))
            audit.ok(not TRUTH.intersection(row) and not TRUTH.intersection(o), 'frame.GT_free.' + str(i))
            audit.eq(ledger['schema'], 'same_sparse_ROLE_local_point_line_ledger_v9', 'frame.ledger_schema.' + str(i))
            packet(row, ledger, p, o, control, audit, counts, 'frame.' + str(i))
        for name, stream in (('local_geometry', new), ('local_ledgers', ledgers), ('parent_geometry', parent), ('parent_observation', obs), ('point_controls', point)):
            audit.eq(next(stream, None), None, name + '.no_extra_population')
        fixed_population(paths['parent:FIXED_GEOMETRY_SEALED.jsonl.gz'], known, audit)
        recorded_receipts(paths, inputs, core, seal, receipt, population, counts, audit)
        audit.eq(counts['local_packets'], 245, 'complete.local245')
        audit.eq({k: binding(p) for k, p in paths.items()}, inputs, 'complete.all_input_bytes_unchanged_after_arithmetic')
        audit.eq(binding(own_path), own_binding, 'complete.own_protocol_unchanged_after_arithmetic')
    except BaseException as error:
        failure = dict(type=type(error).__name__, message=str(error))
    complete = failure is None and counts['local_packets'] == 245
    passed = complete and audit.failure_count == 0
    write_new(output/OUTPUTS[2], dict(schema='supplemental_sparse_local_point_line_scalar_checks_v9',
        complete=complete, passed=passed, own_protocol=own_binding, checker=inputs['checker'], inputs=inputs,
        limits=LIMITS, checks=audit.checks, failure_count=audit.failure_count, failures=audit.failures,
        exception=failure, counts=dict(counts), max_scalar_absolute_difference=audit.max_difference,
        wall_seconds=time.monotonic()-began, new_model_GT_image_optimizer_PnP_SVD_calls=0,
        full_candidate_witnesses_retained_in_original_geometry=True, full_population_rows_retained=0,
        original_geometry_unchanged=True if passed else 'checked only if reached final binding comparison',
        first_failure_preserved=True, automatic_retry=False))
    print('SPARSE_LOCAL_SCALAR', 'PASS' if passed else 'FAIL', audit.checks, dict(counts), flush=True)
    if not passed:
        raise SystemExit(1)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('stage', choices=('freeze', 'run'))
    parser.add_argument('--input', type=Path, default=PRIVATE/'geometry')
    parser.add_argument('--output', type=Path, default=DOC)
    parser.add_argument('--protocol', type=Path, default=DOC/'PROTOCOL.json')
    parser.add_argument('--parent', type=Path, default=PARENT)
    parser.add_argument('--point-parent', type=Path, default=POINT)
    parser.add_argument('--cohort', type=Path, default=COHORT)
    args = parser.parse_args()
    (freeze if args.stage == 'freeze' else run)(args)


if __name__ == '__main__':
    main()
