agnostic_nms: false
amp: true
angle: 1.0
augment: false
auto_augment: randaugment
batch: 32
bgr: 0.0
box: 7.5
cache: false
cfg: null
classes: null
close_mosaic: 10
cls: 0.5
cls_pw: 0.0
compile: false
conf: null
copy_paste: 0.0
copy_paste_mode: flip
cos_lr: true
cutmix: 0.0
data: <bundle>/datasets/ft_m/data.yaml
degrees: 0.0
deterministic: true
device: 0,1
dfl: 1.5
dnn: false
dropout: 0.0
dynamic: false
embed: null
end2end: null
epochs: 40
erasing: 0.4
exist_ok: false
fliplr: 0.0
flipud: 0.0
format: torchscript
fraction: 1.0
freeze: null
half: false
hsv_h: 0.015
hsv_s: 0.5
hsv_v: 0.35
imgsz: 640
int8: false
iou: 0.7
keras: false
kobj: 1.0
line_width: null
lr0: 0.002
lrf: 0.01
mask_ratio: 4
max_det: 300
mixup: 0.0
mode: train
model: <bundle>/runs/stage_a_m_640_b32_seed42/weights/best.pt
momentum: 0.937
mosaic: 0.15
multi_scale: false
name: ft_m_real157_neg259_synth12k
nbs: 64
nms: false
opset: null
optimize: false
optimizer: SGD
overlap_mask: true
patience: 0
perspective: 0.0
plots: true
pose: 12.0
pretrained: true
profile: false
project: <bundle>/runs_ft
rect: false
resume: false
retina_masks: false
rle: 1.0
save: true
save_conf: false
save_crop: false
save_frames: false
save_json: false
save_period: 5
save_txt: false
scale: 0.25
seed: 42
shear: 0.0
show: false
show_boxes: true
show_conf: true
show_labels: true
simplify: true
single_cls: true
source: null
split: val
stream_buffer: false
task: pose
time: null
tracker: botsort.yaml
translate: 0.1
val: true
verbose: true
vid_stride: 1
visualize: false
warmup_bias_lr: 0.1
warmup_epochs: 1.0
warmup_momentum: 0.8
weight_decay: 0.0005
workers: 4
workspace: null
